### ISSUE TITLE
Crash looking up NPCs player has not met yet.

### ISSUE THREAD

**Issue by mattfeldman** [Pathoschild/LookupAnything#10]
Before the player has met an NPC (reproduced by running on a new save) you can go to the calendar in town and lookup NPCs you haven't met. The failing reference is in the player's friendship's here: https://github.com/Pathoschild/LookupAnything/blob/master/LookupAnything/Framework/Subjects/CharacterSubject.cs#L69-L72 

I suggest that we render a `You haven't met this NPC yet` field now for this case.  An alternative I suppose is to suggest schedules #4 / where you can meet the NPC.

**Comment by Pathoschild** [comment]
Fixed in the upcoming 1.5 release via 5b65e2152f1c87171f8e675f780d8d1889fa0f72.
