### ISSUE TITLE
[Lookup Anything] Special fishing area names are not shown

### ISSUE THREAD

**Issue by b3nk3lly** [Pathoschild/LookupAnything#1034]
**Describe the bug**
When looking up a fish, any "special" locations where the fish can be caught are shown as empty strings. By "special" locations, I mean the locations of the legendary fish or any floors in the mines.

**To Reproduce**
(On Stardew 1.6.9 beta)
1. Lookup a legendary fish or a fish that is caught in the mines.
2. See an empty string in "locations" under "Spawn Rules".

**Log file**
https://smapi.io/log/9b203f9fdeac4de3835a7f093dd4f505

**Screenshots**
<img width="626" alt="image" src="https://github.com/user-attachments/assets/2d92e5c4-2812-4e15-bd18-3858358ff82e">
<img width="627" alt="image" src="https://github.com/user-attachments/assets/4c99c989-5603-4f40-a297-a91b55163525">
<img width="626" alt="image" src="https://github.com/user-attachments/assets/346caa58-7599-4620-868b-fe0792fbf2cb">
<img width="626" alt="image" src="https://github.com/user-attachments/assets/65d528dc-7484-4490-aa45-e76ed41ccf08">

**Comment by Pathoschild** [comment]
Fixed via #1035 in the upcoming Lookup Anything 1.46.0. Thanks again for the help!
