### ISSUE TITLE
[Chests Anywhere] add localization ru.json

### ISSUE THREAD

**Issue by vanja-san** [Pathoschild/LookupAnything#104]
Added localization > [**_ru.json_**](https://github.com/vanja-san/LocalizationMods/tree/master/ChestsAnywhere)

**Comment by Pathoschild** [comment]
@vanja-san Thanks! I added the translations to the next release. :)

**Comment by Pathoschild** [comment]
@vanja-san Are you interested in helping translate future mod releases too?
