### ISSUE TITLE
[Content Patcher][Bug] Tilesheets being incorrectly ordered on Linux leading to Map Load blocks.

### ISSUE THREAD

**Issue by BaconCatBug** [Pathoschild/LookupAnything#1048]
**Describe the bug**
When loading maps via SMAPI/Content patcher on Linux, it gives a SMAPI blocked a 'X' map load: the 'Y' content pack reordered the original tilesheets, which often causes crashes. This error does not occur on Windows/Proton.

**To Reproduce**
Install Stardew Valley Expanded/SMAPI on Linux
Run the game.
Get Error.
Repeat but via Proton/Windows.
No Error.

**Log file**
[Linux](https://smapi.io/log/1b6631599428488aa64bdf68b64d7645)
[Windows/Proton](https://smapi.io/log/52ebef98ff04432f81c6048a515a6192)

**Screenshots**
Thanks to atravita on Discord, it's been found to be due to on Linux the sorting being case sensitive, but on Windows it is sorting in the correct order as case insensitive.

https://dotnetfiddle.net/eDXnX7

![image](https://github.com/user-attachments/assets/176c3413-afe4-4340-bb15-ae27ed64990a)

The Default/Ordinal Ignore Case Sort is  the correct order for Maps/HaleyHouse (1, 2, p) which is being returned on Windows/Proton, but the Ordinal Sort is what is being returned on Linux (1, 2, VanillaFurniture)

**Comment by Pathoschild** [comment]
Hi! The inconsistent sorting is an issue with the base game, not Content Patcher. However it won't be an issue anymore in the upcoming Stardew Valley 1.6.9, which no longer accesses tilesheets by index only.

**Comment by BaconCatBug** [comment]
Hey there, my apologies, it turns out it was a broken ICU install on linux, nothing to do with the game or content patcher. Sorry for taking up your time.

**Comment by Pathoschild** [comment]
No worries! I just made a change in the upcoming Stardew Valley 1.6.9 so it'll sort by `OrdinalIgnoreCase` instead of `CurrentCulture`, which should mitigate issues like that.
