### ISSUE TITLE
[Automate] Feature Request: Add compatibility config to ignore Luremaster and still bait crab pots

### ISSUE THREAD

**Issue by BaconCatBug** [Pathoschild/LookupAnything#1050]
Some mods such as Walk of Life make changes to the vanilla Luremaster profession, making the behaviour of no longer baiting crab pots undesirable. Could it be possible to add a compatibility/debug config option to keep baiting pots even if you have the Luremaster profession?

**Comment by Pathoschild** [comment]
Hi! The upcoming Stardew Valley 1.6.9 adds a `CrabPot.PlayerNeedsBait()` method, which Lookup Anything now uses. Once Walk of Life is updated to patch the method, that should no longer be an issue. Thanks for reporting it!
