### ISSUE TITLE
[Tractor Mod] pt-BR Translation 

### ISSUE THREAD

**Issue by TaelFayre** [Pathoschild/LookupAnything#114]
I made this translation while i was translating some of my other mods(just to send them to the original mod authors as some kind of support). I normally play the game in english, but y'know, sharing is caring.
(i had to create a zip file to attach it here)

[pt-Br Tractor Mod.zip](https://github.com/Pathoschild/StardewMods/files/1389066/pt-Br.Tractor.Mod.zip)

**Comment by Pathoschild** [comment]
Hi @TaelFayre. Thanks for the translations! Another player already submitted Portuguese translations for Tractor Mod in the upcoming version, but maybe you can review and let me know which versions are best?

Your version:
```json
{
  "buff.name": "Poder do trator",
  "garage.name": "Garagem para trator",
  "garage.description": "Uma garagem para guardar seu trator. Trator Incluso!"
}
```

Current version:
```json
{
  "buff.name": "Energia do Trator",
  "garage.name": "Garagem do Trator",
  "garage.description": "Uma garagem pra guardar seu trator. Trator incluído!"
}
```

**Comment by TaelFayre** [comment]
Both versions are pretty much the same with some small differences, mine is a bit more formal and correct tho, either one will work fine for the mod, most people ignore the grammatical errors, so no big deal.

**Comment by Pathoschild** [comment]
@TaelFayre Thanks! I'll use your translations then.

Would you be willing to translate new text for future mod updates too? (I'll ping you on GitHub when any of the text changes.)

**Comment by TaelFayre** [comment]
Sure, i'm always willing to help modders(also i love your tractor mod, it's so god damn useful)

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming Tractor Mod 4.2. Thanks again!
