### ISSUE TITLE
[Chests Anywhere] review translations in 1.12

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#116]
Review translations in the Chests Anywhere 1.12 release.

**Comment by Pathoschild** [comment]
Chests Anywhere 1.12 adds support for Junimo huts. Here's the default name for a Junimo hut:
> Junimo Hut #{{number}}

<details><summary>expand for translations (see below for newer)</summary>
Translations:

language   | translation                      | status
---------- | -------------------------------- | -----------------
Chinese    | ~~_{{number}}祝尼魔小屋_~~<br />_{{number}}座祝尼魔小屋_            | ✓ corrected by yuwenlan
German     | _Junimo Hütte #{{number}}_       | ✓ reviewed by @d0x7
Portuguese | _Cabana dos junimos #{{number}}_ | ✓ reviewed by @TaelFayre 
Russian    | _Юнимос #{{number}}_             | ❑ **not reviewed**
Spanish    | _Cabaña junimo #{{number}}_      | ❑ **not reviewed**

</details>

**Comment by Pathoschild** [comment]
@TaelFayre Can you check the Portuguese translation for me? ^

@ThomasGabrielDelavault Can you check the Spanish translation above? If you have time, it'd be great if you could translate this for Tractor Mod too:
```json
{
  "buff.name": "Tractor Power",
  "garage.name": "Tractor Garage",
  "garage.description": "A garage to store your tractor. Tractor included!"
}
```

**Comment by TaelFayre** [comment]
The Portuguese translation is good to go.

**Comment by Pathoschild** [comment]
I added support for the shipping bin in Chests Anywhere 1.12 too, so there's one new translation:


language   | default Junimo Hut name          | shipping bin name | status
---------- | -------------------------------- | ----------------- | ---------------------------
_default_  | _Junimo hut #{{number}}_         | _Shipping bin_    | ✓
Chinese    | ~~_{{number}}祝尼魔小屋_~~<br />_{{number}}座祝尼魔小屋_| _出货箱_ | ✓ translated by yuwenlan.
German     | _Junimo Hütte #{{number}}_       | ?                 | ↻ partly reviewed by @d0x7.
Portuguese | _Cabana dos junimos #{{number}}_ | _Caixa de Remessas_ | ✓ translated by @TaelFayre.
Russian    | _Юнимос #{{number}}_             | ?                 | ❑ **not reviewed**
Spanish    | _Cabaña junimo #{{number}}_      | ?                 | ❑ **not reviewed**

@d0x7 @TaelFayre Can you take a look? These should be the last ones for this release, sorry!

**Comment by TaelFayre** [comment]
pt-BR Shipping bin = Caixa de Remessas

**Comment by Pathoschild** [comment]
Thanks!

**Comment by Pathoschild** [comment]
Closing for 1.12 release. The remaining messages can be translated in a future release; they'll appear in English in the meantime.
