### ISSUE TITLE
[Lookup Anything] fix grammar in Portuguese translations

### ISSUE THREAD

**Issue by TaelFayre** [Pathoschild/LookupAnything#120]
I opened the translation just to see how good it was, then i got interested in fixing some words that weren't translated and some other small things.
 Most of it was already completed, but i went through all the lines changing between the default and the translation to see if there was a better translation to it
[pt.zip](https://github.com/Pathoschild/StardewMods/files/1404150/pt.zip)

(I'm new to github, if there is a better way to send the translation without having to create a zip file and attaching it here, please tell me!)

**Comment by Pathoschild** [comment]
Thanks! You can propose an edit directly on GitHub:

1. [Find the file on GitHub](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/pt.json).
2. Click this button:
   > !['edit this file' button](https://user-images.githubusercontent.com/230581/31854050-32b1e4e0-b661-11e7-814b-a30fb58897fb.png)
3. Make your changes in the textbox.
4. At the bottom, click "Create a new branch for this commit and start a pull request".
5. Submit the pull request.

Then I just need to approve the request, and you'll be credited in the code history. :)

**Comment by Pathoschild** [comment]
Added in `develop` for the upcoming Lookup Anything 1.17 release. Thanks!
