### ISSUE TITLE
[Tractor Mod] optional colors

### ISSUE THREAD

**Issue by TaelFayre** [Pathoschild/LookupAnything#122]
So.... I'm curious if people would actually want to change their tractor color(i changed mine to purple using photoshop) so if you plan to add optional files for people like me, just tell me and i'll start recoloring it and send it to you like a mega pack or something(i have a lot of free time so i can do it for you while you work on something else)

**Comment by Pathoschild** [comment]
Hi @TaelFayre. Retextures are welcome in [the mod's discussion thread](https://community.playstarbound.com/threads/tractor-mod.136649). I'm not planning to bundle multiple versions for now, but if you mention "I agree to release these under the same MIT license as Tractor Mod" in your post I'll be able to bundle them later. :)
