### ISSUE TITLE
[Lookup Anything] show fish season

### ISSUE THREAD

**Issue by TaelFayre** [Pathoschild/LookupAnything#123]
I was thinking about this idea yesterday, it would be really useful for those who want to complete the fishing bundle in the 1th year. i don't think it would be hard to add it into the mod considering that crops also have their season of growth added in their info.

**Comment by Pathoschild** [comment]
Hi @TaelFayre. Thanks for the suggestion! Fish spawning rules are harder than crop seasons, but it is possible. There's already a ticket at #82 to look into it. :)
