### ISSUE TITLE
[Tractor Mod] Flowers lose color when harvested with tractor

### ISSUE THREAD

**Issue by SpringsSong** [Pathoschild/LookupAnything#133]
When harvesting flowers with the scythe or tractor, the color of flowers is wiped and replaced with whatever the "standard" color is.  While *I* personally don't mind (only one color means less worrying about space in one's inventory), others might like to be able to maintain the color of their flowers when harvesting flowers with the tractor (for displays and such, perhaps).  If it's not too difficult, perhaps make it a configurable option:
```json
"StandardizeFlowers": false
```
OR

```json
"ColoredFlowers": true
```

**Comment by Pathoschild** [comment]
@SpringsSong That one isn't a bug with Tractor Mod, which keeps the colours correctly:
> ![](https://user-images.githubusercontent.com/230581/36879880-d2facdf6-1d93-11e8-9522-6b450e7b0b61.png)

It sounds like you have a harvest-with-scythe mod, which is interfering with the flower colors. I suggest reporting it to that mod's author.
