### ISSUE TITLE
[Automate] Bad interaction with shipping container

### ISSUE THREAD

**Issue by iamthad** [Pathoschild/LookupAnything#140]
The behavior of automation chains attached to the shipping container seems to be undesirable. 

For example, place a chest and then a mayonnaise machine to the left of the shipping container. When more than one egg is placed into the chest, one egg is added to the mayonnaise machine as expected, but the rest are dumped into the shipping container. 

The behavior I would expect (and want) is that the finished mayonnaise goes into the shipping container, but not the raw eggs.

Perhaps this is a consequence of the recent changes allowing multiple interconnected machines?

**Comment by Pathoschild** [comment]
@iamthad That's the current expected behaviour. The shipping bin is just another 'machine' in the group, so it'll consume all the shippable items available. I plan to support what you're describing with transport pipes in a future version (see #61). 🙂
