### ISSUE TITLE
[Automate] error drawing overlay

### ISSUE THREAD

**Issue by changbowen** [Pathoschild/LookupAnything#145]
Thanks for the great mods!
The automation overlay of the farm refused to show though after a few days. (Prompts something went wrong.)
It still works at the farmhouse.
Logs: https://log.smapi.io/dYM3YV1b

**Comment by changbowen** [comment]
Looks like the placing of the below seed maker causes the issue:
![image](https://user-images.githubusercontent.com/15975872/34439110-9d8019ca-ece6-11e7-9d10-0fe0cc3b651d.png)

Also the below setup works. But if I place another chest if front of me, the error occurs. Looks like somehow the seed maker and the silo are connected together..
![image](https://user-images.githubusercontent.com/15975872/34439412-c918576c-ece8-11e7-936a-02a53437886a.png)

**Comment by Pathoschild** [comment]
@changbowen Can you post a [zip of your save](https://stardewvalleywiki.com/Saves#Find_your_save_files) which has that error?

**Comment by changbowen** [comment]
@Pathoschild here it is: 
[Ukong_173095958.zip](https://github.com/Pathoschild/StardewMods/files/1594357/Ukong_173095958.zip)

dont mind the bad words in the animal names :)

**Comment by Pathoschild** [comment]
@changbowen Can you confirm it doesn't happen with this version?
* ~~Automate 1.9-alpha.20171230.zip~~

**Comment by changbowen** [comment]
No it doesn't happen now. 👍 👍 👍 
When will the new versions (including Chest Anywhere) be released :)

**Comment by Pathoschild** [comment]
Thanks for testing! The Automate and Chests Anywhere updates will be in the next couple of days. :)
