### ISSUE TITLE
[Chests Anywhere] Add exception to unlimited access

### ISSUE THREAD

**Issue by xangriaz** [Pathoschild/LookupAnything#147]
I like the idea of balanced mode, but I actually want to only prevent myself from accessing chests from within the mines. Would it be possible to add a location that is not allowed, rather than listing those that are?

**Comment by Pathoschild** [comment]
Sure, a disable-in-locations option makes sense.

**Comment by Pathoschild** [comment]
Done in `develop` for the next release. Thanks for the suggestion!
