### ISSUE TITLE
[Chest Anywhere] Browse through chests by mouse scrolling?

### ISSUE THREAD

**Issue by changbowen** [Pathoschild/LookupAnything#151]
Is it possible to use the mouse scroll wheel to browse through the chests?

**Comment by Pathoschild** [comment]
@changbowen You can navigate quickly using the arrow keys on the keyboard. Is that sufficient?

**Comment by changbowen** [comment]
@Pathoschild is it supported by the framework to use mouse wheel up / down instead of the key press?

**Comment by Pathoschild** [comment]
Yep, SMAPI does support handling mouse scroll.

**Comment by changbowen** [comment]
what keybinding value to use in the config.json file?
i cannot find values for mouse wheel action in https://stardewvalleywiki.com/Modding:Key_bindings

**Comment by Pathoschild** [comment]
SMAPI has an event for mouse changes, but the mod needs to be programmed to support it. That's why I was asking if you knew about the keyboard navigation — if that was sufficient, there'd be no reason to look into support for mouse wheel scrolling. :)

**Comment by changbowen** [comment]
it would be a nice addition for me :)
but if it is too much trouble i can live with the keyboard navigation too.

**Comment by Pathoschild** [comment]
Done via #291 for the upcoming Chests Anywhere 1.13-beta.7 (thanks to @mattfeldman!). This adds two shortcuts:

keys | result
---- | ------
`Left Control` + scroll mouse wheel | scroll chest dropdown.
`Left Alt` + scroll mouse wheel | scroll category dropdown.
