### ISSUE TITLE
[Lookup Anything] Include placed Furniture

### ISSUE THREAD

**Issue by Platonymous** [Pathoschild/LookupAnything#173]
Look up furniture that has been placed on the map.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming release.

It doesn't show much info by default:
> ![](https://user-images.githubusercontent.com/230581/36131093-28dca2e8-103e-11e8-84b8-23a8a95980bb.png)

But there's more info with data mining enabled:
> ![](https://user-images.githubusercontent.com/230581/36131126-4ec39e62-103e-11e8-9b5e-ec213eb6efb4.png)
