### ISSUE TITLE
[Lookup Anything] Odd bug when looking up custom machines

### ISSUE THREAD

**Issue by Platonymous** [Pathoschild/LookupAnything#174]
Looking up a custom machine only seems to work when it was placed in the last session.

https://log.smapi.io/YgFBhSJm

Error can be recreated by doing this:
- Load a savegame
- Place a Custom Machine (exp. Butter Churn) either from Crafting or CJB
- Look up the machine in the inventory (No Error)
- Place the machine on the map
- Look up the placed machine (Error)
- save and then close the game.
- Restart the game and load the same savefile
- Look up the placed machine (No Error)
- Place another machine from Crafting or CJB and look that up (Error)
(saving the game after placing the machine does not remove the error from the machine lookup, only closing and reloading does)

[CustomFarmingRedux.zip](https://github.com/Pathoschild/StardewMods/files/1665451/CustomFarmingRedux.zip)
[PyTK.zip](https://github.com/Pathoschild/StardewMods/files/1665452/PyTK.zip)

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming release. This needs the Custom Farming Redux API changes from platonymous/Stardew-Valley-Mods#21.
