### ISSUE TITLE
[Tractor Mod] Add more granular feature options

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#189]
Add more granular options for choosing which features are enabled in `config.json`.

**Comment by Pathoschild** [comment]
Possible schema:
```json
{
  "PassThroughTrellisCrops": false,
  "Distance": 1,
  "TractorSpeed": -2,
  "MagneticRadius": 384,
  "BuildUsesResources": true,
  "BuildPrice": 150000,
  "HighlightRadius": false,
  "Controls": {
    "SummonTractor": "T",
    "HoldToActivate": ""
  },
   "StandardAttachments": {
      "Axe": {
         "CutFruitTrees": false,
         "CutTrees": false,
         "ClearLiveCrops": false,
         "ClearDeadCrops": true,
         "ClearDebris": true
      },
      "Fertilizer": {
         "Enable": true
      },
      "GrassStarter": {
         "Enable": true
      },
      "Hoe": {
         "TillDirt": true
      },
      "Pickaxe": {
         "ClearDebris": true,
         "ClearDeadCrops": true,
         "ClearDirt": true,
         "BreakFlooring": false
      },
      "Scythe": {
         "HarvestForage": true,
         "HarvestCrops": true,
         "HarvestFlowers": true,
         "HarvestFruitTrees": true,
         "HarvestGrass": true,
         "ClearDeadCrops": true,
         "ClearWeeds": true
      },
      "Seeds": {
         "Enable": true
      },
      "WateringCan": {
         "Enable": true
      },
      "SeedBagMod": {
         "Enable": true
      }
   },
  "CustomAttachments": []
}
```

**Comment by Fox536** [comment]
Ok might I suggest (purely because I don't know if it's possible lol), under the Axe tab something like
`"Axe": {
         "CutFruitTrees": false,
         "CutTrees": false,
         **"CutTappedTrees": false,**
         "ClearLiveCrops": false,
         "ClearDeadCrops": true,
         "ClearDebris": true
      },`

It would be helpful, not really mandatory just a thought. 

Also do you ever accept help from outside coders? I'm getting into the coding side and might be able to help out if you want/need any.

**Comment by Pathoschild** [comment]
Thanks, having an option for tapped trees makes sense. And yep, pull requests are welcome! It's best to discuss the changes you want to make first though. :)

**Comment by Fox536** [comment]
Would you prefer to discuss them here or on nexus?

**Comment by Pathoschild** [comment]
Here is fine. Were you thinking of implementing this ticket?

**Comment by Fox536** [comment]
I'd love to see if I can, I'll take a better look at the code when I get some time tomorrow, it's be a great learning experience either way.  I already saw somethings from your automate mod that will help me with making bee hives work indoors.

**Comment by Fox536** [comment]
Ok I believe I got it done, everything works. It looks stable let me know what you think.

Edit: Well I have it coded but I'm not sure how to submit a push or a pull request lol.

**Comment by Pathoschild** [comment]
On the [repo page for your fork](https://github.com/Fox536/StardewMods), click this button: 
> ![](https://user-images.githubusercontent.com/230581/36766105-64884408-1c02-11e8-8660-7041479fd716.png)

See _[about pull requests](https://help.github.com/articles/about-pull-requests/)_ in the GitHub docs for more info. Feel free to ask if something is unclear.

**Comment by Fox536** [comment]
I found an article showing that I needed to click the fork button, instead of just cloning the repository like I had assumed, but I sent the request so it should be there when you get time to look it over.

**Comment by Pathoschild** [comment]
Done via #193. Thanks!
