### ISSUE TITLE
[Lookup Anything] mention achievements a recipe is needed for

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#195]
When looking up an item that's used in a recipe, mention whether that recipe is needed for an achievement (e.g. Gourmet Chef or Craft Master).

[Requested on Nexus](https://www.nexusmods.com/stardewvalley/mods/541/?tab=posts&jump_to_comment=57768116).

**Comment by Saklad5** [comment]
Could this be made to disappear if the requirement has been fulfilled, like with bundles?

**Comment by Pathoschild** [comment]
Yep.

**Comment by Pathoschild** [comment]
Done via #355 in `develop` for the upcoming Lookup Anything 1.21. Thanks to @watson81!
