### ISSUE TITLE
[Content Patcher] add negative conditions

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#219]
Content Patcher 1.3 added conditions with the `When` field. Extend that to support negative conditions with `WhenNot`:

```js
// any day in summer except the 11th
"When": {
   "Season": "Summer"
},
"WhenNot": {
   "Day": 11
}
```

**Comment by RuiNtD** [comment]
Your idea could cause problems if someone tried to set both a positive and negative condition for the same condition type. For example:
```javascript
"When": {
   "Season": "Summer"
},
"WhenNot": {
   "Season": "Summer"
}
```

Another idea is to mark a condition as negative if it starts with `!`. For example:
```javascript
"When": {
   "Season": "!Summer, Winter",
   "Day": "!11, 24"
}
```
Which means when it isn't the 11th or 24th of summer or winter.

**Comment by Pathoschild** [comment]
Contradictory conditions would work fine (insofar as they'll correctly never apply). Supporting negation within the condition could work too (though of course they could do `"Season": "Summer, !Summer"` too).

(I think a `!` flipping all values would be confusing though. If it's inside the condition list, it would only be for the condition it's in front of.)

**Comment by Pathoschild** [comment]
Per discussion on Discord, the preferred format is:
```json
"When": {
   "Season": "Summer",
   "Not:Day": "11"
}
```

**Comment by Pathoschild** [comment]
That's now handled by the subkey format added in Content Patcher 1.5:
```js
"When": {
   "Day:11": false // not day 11
}
```
