### ISSUE TITLE
Add support for Linux and Mac

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#22]
Add support for Linux and Mac. This involves the following changes:

- Preparation:
  - [x] Add the default Linux/Mac paths to the game path detection.
  - [x] Document the compile steps automated by the Windows-only build script.
- Adjust build process:
  - [x] Detect the platform during the build process.
  - [x] On Linux/Mac, swap the XNA references for MonoGame.
  - [x] On Linux/Mac, disable the mod deploy script.

Thanks to @Kriana and @vizv for doing the initial research and creating a [Mac fork](https://github.com/kriana/LookupAnything) and [Linux fork](https://github.com/vizv/LookupAnything) respectively!

**Comment by kriana** [comment]
:3
I'm here to help and test!

**Comment by Pathoschild** [comment]
Lookup Anything is now almost crossplatform as of 97fb9555c5f38f03d32253190964d7cd586ee482 (including updated compile instructions for Linux/Mac users), with help from @kriana for testing.

The only remaining issue is that MonoDevelop can't find the references — I'm not sure yet if it's an issue with `<GamePath>` or something with the references themselves.

**Comment by Pathoschild** [comment]
I created [an experimental NuGet package](https://github.com/Pathoschild/Stardew.ModBuildConfig) that automates the project/build configuration for crossplatform mods.

To write a crossplatform mod, you just:
* create an empty library project;
* reference the NuGet package;
* and write your code.

I tentatively migrated Lookup Anything to this new framework.

**Comment by Pathoschild** [comment]
Confirmed working on Mac by @kriana; Linux pending.

**Comment by vizv** [comment]
Cool! I don't have time right now but I'll check that.

**Comment by Pathoschild** [comment]
Confirmed working on Linux by @rumangerst. More testing welcome, to make sure it works on all computers. :)

**Comment by Pathoschild** [comment]
Linux/Mac modding is now documented (see _[using mods](http://canimod.com/guides/using-mods)_ and _[creating a SMAPI mod](http://canimod.com/guides/creating-a-smapi-mod)_), and Lookup Anything is now crossplatform. The next version will be officially released on Linux, Mac, and Windows.
