### ISSUE TITLE
[Chests Anywhere] beta: items in shipping bin aren't saved

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#231]
Items added to the shipping bin in Stardew Valley 1.3 beta aren't persisted.

Reported [in the forums](https://community.playstarbound.com/threads/smapi-chests-anywhere.122603/page-13#post-3269171).

**Comment by MailPerson** [comment]
While I'm sure you've already recorded this:

Items added to the shipping bin through the world (by throwing your in hand item into the bin) are persisted. They add to the bin as they should, multiple items will be recorded in succession and none are deleted. The issue only occurs when an item is added through the open chest menu. 

To make things more interesting, if an item is tossed into the box, and then duplicates of that item are added, they'll stack properly. However, if those items are removed and added via the menu they'll disappear. Adding the same item back by throwing it in reveals a filled invisible space.

As such:
![image](https://user-images.githubusercontent.com/38899220/39502759-a6b715fa-4d87-11e8-80a4-0b7f3a50a3bd.png)

Right-clicking to add one item to the cursor stack also deletes the item.

**Comment by Pathoschild** [comment]
Fixed via #237 for the upcoming Chests Anywhere 1.13-beta.2.
