### ISSUE TITLE
[Lookup Anything] beta: Freezes in multiplayer when day ends

### ISSUE THREAD

**Issue by victinipples** [Pathoschild/LookupAnything#234]
In Stardew valley 1.3 beta multiplayer using the 1.19 beta and no other mods, when the day ends by players sleeping the game freezes.

**Comment by victinipples** [comment]
btw sorry if this is not the correct place/way to report this haha

**Comment by Pathoschild** [comment]
@victinipples That's a SMAPI bug fixed in the upcoming SMAPI 2.6-beta.3. :)
