### ISSUE TITLE
[Content Patcher] Seasonal fence errors

### ISSUE THREAD

**Issue by oomps62** [Pathoschild/LookupAnything#241]
When placing fences that are tied to season, new fences will go down with the retexture, but upon closing and reopening SMAPI,  As shown in the screen shot below, even though old fences will have the vanilla texture, newly placed fences will go down with the retexture.

Another person said that if they placed the "summer" fence down in summer, that the retexture carried over into fall - still displaying the summer texture.

![seasonalfences](https://user-images.githubusercontent.com/15027351/39613543-919b56e8-4f2d-11e8-8e5d-f14142b1a1fa.png)

This is the content pack in question:

[SeasonalPaths.zip](https://github.com/Pathoschild/StardewMods/files/1973307/SeasonalPaths.zip)

**Comment by Pathoschild** [comment]
Fixed in SMAPI 2.6-beta.7. Thanks for reporting it!
