### ISSUE TITLE
[Lookup Anything] beta: not compatible with latest SDV beta

### ISSUE THREAD

**Issue by Kevin-Mok** [Pathoschild/LookupAnything#242]
Both are the latest versions posted. [Here's the log.](https://log.smapi.io/sA9qWwgg)

**Comment by f4iTh** [comment]
It just seems to need a quick recompile. [Log if it's even needed](https://log.smapi.io/fCR3X4tj). Yes, ignore the _errors_, they're supposed to be there (except for one but that's fine, the mod isn't even out yet).

**Comment by Pathoschild** [comment]
Thanks! Fixed as part of the the upcoming Lookup Anything 1.19-beta.2.
