### ISSUE TITLE
Automate simply not working

### ISSUE THREAD

**Issue by irlHamster** [Pathoschild/LookupAnything#246]
Simply put, automate isn't working. I loaded it up, the console said that it was all fine and working, but when I load it in my beta (I have the correct beta one) nothing works. It wont take items from chests or put them in chests.

**Comment by irlHamster** [comment]
I might have found a temporary patch, I broke a few of my seedmakers to make it into a more easily afk-farmable setup so I could just idly move my hand around while holding rightclick, and it seemed to fix after I broke it.

**Comment by Pathoschild** [comment]
Hi @irlHamster. That sounds like #233, which is fixed in the upcoming Automate 1.10-beta.2. Thanks for reporting it!
