### ISSUE TITLE
[Lookup Anything] Add support for buildings

### ISSUE THREAD

**Issue by Sakorona** [Pathoschild/LookupAnything#257]
Currently, if you try to look at say a mill, or a silo, it can't pull the building information up. Is it possible to add this to a later release?

**Comment by Pathoschild** [comment]
Sure. What kind of information would you want displayed?

**Comment by Sakorona** [comment]
I mean, in general, I think it should display processing information if it's that type of building, or what it holds for a silo. 

I'm wondering what information it should display for a shed, or a barn, or coop or slime hutch though..

**Comment by RuiNtD** [comment]
For a coop (for example), you could show what animals are stored in that coop (along with their names, pet status, and mood) and how many are inside (as opposed to outside). You can also show how many eggs are waiting to be picked up, how much hay is on the feeding bench (if you don't have the autofeeder), and the status of the incubator.

**Comment by Pathoschild** [comment]
Some possible fields (not necessarily all in the initial release):
* general:
  * [ ] description
  * [x] 'under construction' completion date
  * [ ] upgrade completion date
* [x] cabin:
  * [x] owner (link to player info)
  * [ ] upgrade level
  * [ ] whether marriage is enabled
  * [ ] whether children are enabled
* [ ] coop/barn:
  * [ ] possible animals (based on upgrade level)
  * [ ] number of animals housed
  * [ ] total capacity
  * [ ] egg incubator status
  * [ ] feed trough status
  * [ ] whether pregnancy is enabled
  * [ ] whether autofeed is enabled
* [ ] Junimo hut:
  * [ ] whether harvesting is enabled
  * [ ] whether items are ready to collect
* [ ] mill:
  * [ ] items ready / being processed
* [x] silos:
  * [x] stored hay
  * [x] total hay
* [ ] slime hutch:
  * [ ] number of slimes houses + total capacity
  * [ ] water trough status
* [x] stable:
  * [x] owner (link to player info)
  * [ ] horse name + location

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming Lookup Anything 1.21:
> ![](https://user-images.githubusercontent.com/230581/50671791-05ec4680-0fa2-11e9-9a1e-eedfc65825b8.png)

These fields are implemented:
* general:
  * translated name + description from blueprint
  * 'under construction' completion date
  * upgrade completion date
* barn/coop:
  * number of animals housed
  * total capacity
  * feed trough status
  * upgrade levels
* cabin:
  * owner (link to player info)
  * upgrade levels
* Junimo hut:
  * whether harvesting is enabled
  * whether items are ready to collect
* mill:
  * items ready / being processed
* silo:
  * stored hay
  * total hay
* slime hutch:
  * number of slimes houses + total capacity
  * water trough status
* stable:
  * owner (link to player info)
  * horse name + location

The egg/slime incubator status might be implemented in a future version.
