### ISSUE TITLE
[Content Patcher] Colour changing fails when farmer_base, or farmer_girl_base are loaded as PNGs

### ISSUE THREAD

**Issue by HanPrower** [Pathoschild/LookupAnything#260]
Whilst porting [Slightly Cuter Character Sprites](https://www.nexusmods.com/stardewvalley/mods/1437) I originally made the farmer_base's PNGs and didn't think much else of it.

The male sprites are invoked with `"Action": "Load"` while the female sprites were invoked with `"Action": "EditImage"` as the mod had skirts, as well.

When using PNGs the colours of the skin and eyes failed to work entirely (only some pixels actually change colour), however upon converting the PNGs directly to XNBs and updating the content.json in kind the colour sliders work correctly.

Oddly the pant layer is unaffected by being a PNG.

**Comment by Pathoschild** [comment]
@HanFox Can you attach a minimal content pack that reproduces the PNG issue?

**Comment by HanPrower** [comment]
Sure, in the attached mod the male is set to XNB and the female is set to PNG.

[Farner Colour Debug.zip](https://github.com/Pathoschild/StardewMods/files/2006256/Farner.Colour.Debug.zip)

**Comment by HanPrower** [comment]
Okay, so I managed to get on my g/fs Windows machine and this seems to be a Linux issue (maybe also Mac).

It's extra frustrating because the XNBs I made with mgs (mono game) seem to throw a load of junk in to the file which Windows does not like.

**Comment by ghost** [comment]
Can confirm this bug also occurs on MacOS.

**Comment by Pathoschild** [comment]
@HanFox @swmbyh That should be fixed in SMAPI 2.8 (via Pathoschild/SMAPI#279). Thanks for reporting it, and feel free to reopen if it still happens with that version.
