### ISSUE TITLE
[Automate] beta: broken in SDV 1.3.11

### ISSUE THREAD

**Issue by red4stone** [Pathoschild/LookupAnything#262]
The commands window reads, "Broken code in Automate.dll: reference to StardewValley.Farmer.professions (field returns NetList<System.Int32,Netcode.NetInt>, not List<System.Int32>)." and Automate does nothing.

**Comment by Pathoschild** [comment]
Yep, today's Stardew Valley 1.3.11 update broke a lot of mods. Right now I'm focusing on SMAPI and figuring out which mods need updates, then I'll start updating mods again.

**Comment by Pathoschild** [comment]
Fixed in the upcoming Automate 1.10-beta.5. Thanks for reporting it!
