### ISSUE TITLE
[Skip Intro] Farmhand's game crashes if host exits by using the close button in the title bar

### ISSUE THREAD

**Issue by danvolchek** [Pathoschild/LookupAnything#268]
This is the same issue as https://github.com/Pathoschild/SMAPI/issues/525. To reiterate what's in that thread: If Skip Intro is installed, and the host player exits the game by using the close button in the title bar, any connected player's games will crash when they return to the title menu.

**Comment by Pathoschild** [comment]
Fixed in the upcoming Skip Intro 1.8-beta.2. Thanks for reporting it!
