### ISSUE TITLE
[Automate] Bee houses only produce wild honey when outside of the farm

### ISSUE THREAD

**Issue by danvolchek** [Pathoschild/LookupAnything#273]
A change in SDV 1.3 lets bee houses look for flowers around them even if the bee houses aren't in the farm. Automate's `BeeHouseMachine` [still has a check](https://github.com/Pathoschild/StardewMods/blob/develop/Automate/Framework/Machines/Objects/BeeHouseMachine.cs#L67) for the current location being a farm before searching for flowers, so it still follows the old SDV 1.2 behavior.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Automate 1.10-beta.6. Thanks for reporting it!
