### ISSUE TITLE
[Automate] [Suggestion] Add Input/Output pipes to Sheds to allow Automation through Sheds

### ISSUE THREAD

**Issue by iMagic16** [Pathoschild/LookupAnything#274]
As title depicts, add an input and output shaft to enable shed integration to automate. A similar input and output shaft would be visible on the interior. This makes for nice, compact farms with Automation

See paint depiction below

![automate suggestion](https://user-images.githubusercontent.com/4530346/40332826-713d8f96-5d4d-11e8-804a-ab98cb33a1c0.png)

**Comment by Pathoschild** [comment]
Thanks for the suggestion! That's one of the features I have planned for transport pipes (#61). :)

**Comment by iMagic16** [comment]
Awesome! How is that coming along?

**Comment by Pathoschild** [comment]
Most of the basic infrastructure is in place, but unfortunately most of my time goes towards SMAPI so I rarely have time to work on it. :(
