### ISSUE TITLE
[Content Patcher] per-save configuration

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#279]
Consider adding a way to support per-save `config.json` settings.

[Requested in the forums](https://community.playstarbound.com/threads/content-patcher.141420/page-5#post-3285524).

**Comment by BlueWind95** [comment]
I think the simplest way to implement this would be with numerous config.json files, under different names for each save, with the form of farmername.config.json. Leave it up to the user to copy the config file, rename it appropriately, and then edit it. Content patcher can, upon load, try to read the playername.config.json file and if it's not found, then it can use the default of config.json. This lets people use just as many different configs as they want, keeping each config simple.

**Comment by Pathoschild** [comment]
I don't have any current plans to add per-save configuration, and it's the sort of thing that can be done using mod managers, so I'll close this as _won't do_.
