### ISSUE TITLE
Add 'advanced mode' that shows raw data

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#29]
Add an optional 'advanced mode' that shows more raw data, including...
* item ID;
* object type;
* NPC's raw friendship/happiness/health/attack/defence values;
* tree health.

**Comment by Pathoschild** [comment]
Here are three possible approaches. (These are raw prototypes, so they might be prettier in the released version.)

1. **Dump _all_ raw data and constants.**  
    Potentially useful for data mining, but also overwhelming. For example, a common mushroom has 152 such fields.
2. **Dump all raw data _except_ constants.**  
   Still useful for data mining (they can look up the constants separately), but much less overwhelming. For example, a common mushroom has 38 such fields:
   ![image](https://cloud.githubusercontent.com/assets/230581/21171376/c9dd48b8-c199-11e6-876a-0c6ad3e01ac5.png)
   ![image](https://cloud.githubusercontent.com/assets/230581/21171406/f0a96b84-c199-11e6-9c69-8b69b877bae6.png)
   ![image](https://cloud.githubusercontent.com/assets/230581/21171421/0433f14c-c19a-11e6-965a-45e4babe42b6.png)
3. **Dump hand-picked data.**
   Less useful for general data mining, but conveys the most important data. Individual fields can be hand-formatted (like the category line), and we can show data that isn't from fields (like the type name).
   ![image](https://cloud.githubusercontent.com/assets/230581/21171604/2b734a2c-c19b-11e6-8d88-f4ded3a40474.png)

**Comment by tstaples** [comment]
I thinking dumping all the data would be better as it may be difficult to determine which properties are important as that varies. Though with all that data it might be hard to sift through so having the option to "pin" properties so they stay at the top of the list would be handy.

Alternatively approach 3 would work just as well and sort of already handles the "pinning" if it allowed you to expand the view to see the rest of the properties. This way the generally deemed important ones can always be "pinned", but access to the less used ones is still available if you need it, without having to wait for the mod to update.

**Comment by Pathoschild** [comment]
@tstaples we can't expand a field interactively (without changing how the mod renders its UI), but we could use a combined approach:
> ![image](https://cloud.githubusercontent.com/assets/230581/21241530/0c55455c-c2de-11e6-9523-e5c353e352fe.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21241572/35569096-c2de-11e6-9c09-ba82fae42bd6.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21241591/488cd6de-c2de-11e6-9fb5-b78ea099c455.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21242143/e508a0c2-c2e0-11e6-9751-940a5ebbf254.png)

**Comment by Pathoschild** [comment]
Done in the `develop` branch for the upcoming 1.9 release. You can enable the fields by setting `ShowDataMiningFields: true` in the `config.json`. Here's how the UI looks in this release pending feedback (demonstrating the sheer amount of data this can make available to data miners):
>![image](https://cloud.githubusercontent.com/assets/230581/21284744/5deb6b92-c3f3-11e6-8993-8d8357254574.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284758/fe1a8b16-c3f3-11e6-880a-c0b63b2f4d16.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284766/13c8cc8e-c3f4-11e6-9114-9d9d00238192.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284768/26f3ae78-c3f4-11e6-8240-7cea87cb510c.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284770/3986f586-c3f4-11e6-9dd5-711a35436db3.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284777/4bd4800a-c3f4-11e6-8ed9-d02aea0bff69.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284779/5e6f3f3e-c3f4-11e6-9368-f21ec0495859.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284783/84b84e1a-c3f4-11e6-917d-ca06a5f8b8fc.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284784/91d2177a-c3f4-11e6-8c6b-ed283c55e257.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284789/9faf1ad2-c3f4-11e6-8ea8-09b69393338c.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284797/cae0188c-c3f4-11e6-942b-aa8476a29c09.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/21284802/e23b7f6c-c3f4-11e6-9d0f-16b1c0712ad7.png)
