### ISSUE TITLE
Simplify gift taste lists

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#30]
The gift tastes list for an NPC can be pretty overwhelming:
> ![image](https://cloud.githubusercontent.com/assets/230581/20873734/b6f72570-ba78-11e6-9126-c8c49b934326.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/20873723/98ff5ace-ba78-11e6-9921-07b79bed8c18.png)
> ![image](https://cloud.githubusercontent.com/assets/230581/20873744/e1780b34-ba78-11e6-887b-7640cd4e5e3a.png)

Use the following rules to simplify it:
* For an item:
  * If everyone likes an item (with up to 2 exceptions), say "everyone" or "everyone (except A and B)" instead of listing them. For example: _everyone (except Abigail and Harvey)_.
* For an NPC:
  * If an NPC likes an entire category (with up to 3 exceptions), say "all <category>" or "all <category> (except A and B)" instead of listing the items. For example: _all crops (except parsnips)_.

**Comment by ShadowKitty42** [comment]
I would like this to be a separate mode you can enable. My reason for this, is I've made it so that owned items are in green text, which suits my needs better than this feature suggestion.

**Comment by Pathoschild** [comment]
Ooh, that sounds useful. Would you be willing to submit a pull request for that?

**Comment by Pathoschild** [comment]
Done via pull request #36, merged into `develop` for the upcoming 1.9 release.

I also revamped custom field rendering so formatting support is built-in (so the lookup menu is simpler and more robust), and further extended this to highlight carried items:
![screenshot of menu with highlighted items](https://cloud.githubusercontent.com/assets/230581/21167522/fea89012-c17a-11e6-906b-48c1eb4a7e63.png)

**Comment by ShadowKitty42** [comment]
Oh wow, that's pretty cool and much better than what I did. Did I spark this idea? lol Cause that makes me glad I contributed.

**Comment by Pathoschild** [comment]
Yep. Thanks! 👍
