### ISSUE TITLE
[Automate] Signs as manufacturing instructions

### ISSUE THREAD

**Issue by mathuin** [Pathoschild/LookupAnything#302]
**Proposal**:  any chest with a sign behind it will try to assemble whatever's on the sign from the parts within its machine group.

**Use case**: Let's say you need a bunch of lightning rods for a project (connecting up a bunch of trees with tappers maybe) but constructing them is monotonous.  It's got three ingredients: iron bar, refined quartz, and bat wings.  The assembly of iron bars and refined quartz is already automated with furnaces, so put a furnace next to a chest and load up the chest with iron ore, quartz, and coal.  With this feature, the final step would be to add a sign behind the chest, tap the sign with a lightning rod, and walk away.

**Additional thoughts**:

- Code must check that whatever's on the sign:
  1. Has a recipe, and
  2. That the farmer knows the recipe.
- Signs can only influence the chest directly in front of them
- Signs should be part of the machine group
- Conflicts between signs can be addressed any way you like as long as it's documented

**Comment by Pathoschild** [comment]
@mathuin Thanks for the suggestion! That's a bit too specialised for Automate, but it could work great as a separate mod once Automate supports mod integrations. I imagine you could do something like this:
```
┌───────┐┌───────┐┌───────┐
│ chest ││  sign ││machine│
└───────┘└───────┘└───────┘
```
The separate mod would turn the sign into a transport pipe, which lets all machine output through in one direction and only the recipe items in the other.
