### ISSUE TITLE
Add a shortcut to scroll between chests in a category

### ISSUE THREAD

**Issue by erinthorn** [Pathoschild/LookupAnything#303]
Hi, I don't think this has been implemented yet, going through your code, but it would be nice if this great mod could be improved by allowing one to easily scroll through the list of chests, preferably with the scroll wheel, since I don't think it's doing anything else when the chests menu is open.

The idea would be that when you have a chest open, you just use the scroll wheel up or down to switch to the previous or next chest in the current chest category.

I assume this is an easy addition, I could probably code it myself, but I hope this is the best way to offer a QoL suggestion that would make a great mod just a little bit better. Thanks for all your work!

**Comment by Pathoschild** [comment]
Thanks for the suggestion! That was added in Chests Anywhere 1.13-beta.7, so you can do this (buttons configurable):

keys | result
---- | ------
`Left Control` + scroll mouse wheel | scroll chest dropdown.
`Left Alt` + scroll mouse wheel | scroll category dropdown.

(See #151 for the original ticket.)

**Comment by erinthorn** [comment]
oh wow, thank you, I should have known it was in there somewhere :)
