### ISSUE TITLE
Inconsistent scrolling while using controller

### ISSUE THREAD

**Issue by ShadowKitty42** [Pathoschild/LookupAnything#31]
I'm a bit of a programmer myself, so I'll provide as detailed info as possible.

All other menus in the game scroll using the Right thumbstick, seemingly moving 1 "unit" (I don't know what it uses) for each time it reads the RightThumbstickUp or RightThumbstickDown "buttons". On other menus, this makes it jump up/down appropriate distances, but on your windows, it only scrolls by 1 pixel at a time. This occurs even if your mod is configured to use different controller buttons for scrolling, but the configured buttons work in the intended manner.

So, would it be at all possible to get the Right thumbstick inputs to scroll more than 1 pixel at a time? Cause I'd rather use that, since the rest of the game uses it also.

**Comment by Pathoschild** [comment]
I don't have a controller, so controller support is a bit patchwork. Pull requests are welcome if you want to improve it. :)

**Comment by ShadowKitty42** [comment]
This can be marked as an enhancement for 1.9, my controller support addition fixes it.

**Comment by Pathoschild** [comment]
Fixed via pull request #37. Thanks!

**Comment by Pathoschild** [comment]
Fixed via pull request #37, merged into `develop` for the upcoming 1.9 release. Thanks!
