### ISSUE TITLE
More convenient lookups for controller users

### ISSUE THREAD

**Issue by ShadowKitty42** [Pathoschild/LookupAnything#32]
The cursor implementation while using a controller is very clunky and often buggy and doesn't work well enough unless you're in a menu. So I have a feature suggestion to solve that.

Whenever I try to lookup something while walking around, moving the thumbstick causes the cursor to appear in seemingly random places, forcing me to use my mouse to save some frustration. Could you make an additional button to configure, that would attempt a lookup on whatever object the player is facing? This would also solve the slight problem of accidentally performing a lookup on your player, when you were trying to get the thing behind them.

**Comment by Pathoschild** [comment]
That's a good idea. I'll use the same logic as the game does when you use tools (i.e. the little red square if you turn on the _Always Show Tool Hit Location_ option). Would you rather a separate hotkey, or a mode you can enable?

**Comment by ShadowKitty42** [comment]
I would prefer a separate hotkey. Also, I think using that logic would only be viable if you move the cursor position before performing the lookup. The reason being, when I'm moving around using controller the cursor is invisible and I often see that red square in some random position that's nowhere near my player. And it often flashes on/off for some reason, until I move the cursor myself, in which case it fixes itself until something causes it to mess up again.

**Comment by Pathoschild** [comment]
Done via pull request #38, merged into `develop` for the upcoming 1.9 release. Thanks!
