### ISSUE TITLE
[Data Layers] add machine overlay to highlight empty vs processing

### ISSUE THREAD

**Issue by MouseyPounds** [Pathoschild/LookupAnything#332]
Reasoning: With large groups of machines (e.g. Kegs and Casks) it can be hard to notice if a machine was missed and is not pulsing.

**Comment by Pathoschild** [comment]
This one is tricky since there's no standard way to differentiate a machine and non-machine in the game code. I could split some of Automate's machine-finding logic, but that'd be messy since Automate handles some special cases like the shipping bin. That wouldn't work for mod machines, too.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming Data Layers 1.5. This uses the new Automate API, so it'll work for custom machines too once Custom Farming Redux is updated to use the API. Thanks for the suggestion!
> ![](https://user-images.githubusercontent.com/230581/49628828-7ceaeb00-f9b4-11e8-891b-7e67df75f6c3.png)
