### ISSUE TITLE
[Lookup Anything] look up cabins

### ISSUE THREAD

**Issue by MouseyPounds** [Pathoschild/LookupAnything#334]
It would be nice if a Lookup could be performed on a Cabin which would list the owning player (possibly with a link to their farmer details) or say if it is unowned.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! Done in `develop` for the upcoming Lookup Anything 1.21:
> ![](https://user-images.githubusercontent.com/230581/50579066-829aeb80-0e0f-11e9-8091-251f5f88d7c9.png)

Some other fields (e.g. date when construction will finish) may be added as part of #257.
