### ISSUE TITLE
[Tractor Mod] - Tractor can place seeds on squares with sprinklers on them

### ISSUE THREAD

**Issue by compro01** [Pathoschild/LookupAnything#335]
See attached screenshots.  Sometimes multi-harvest crops (Blueberries in this case.  Haven't yet tested with others) will retain the "ready for harvest" graphic after being harvested using the tractor scythe, but it only appears to happen for crops that are directly adjacent and north of a sprinkler (at least iridium ones.  Haven't tested with other sprinklers).  The graphic state remains until the next harvest, including persisting through exiting and restarting the game.  Console shows no errors during harvesting.

Looks unharvested...
![Looks unharvested](https://user-images.githubusercontent.com/2030521/47598170-61bca280-d955-11e8-92f8-ba1a84b5d76f.png)

But it can't be interacted with and UI Info Suite reports it is growing.
![But it can't be interacted with and UI Info Suite reports it is growing](https://user-images.githubusercontent.com/2030521/47598169-61bca280-d955-11e8-994e-6d020e4f57cb.png)

Using Tractor Mod 4.5 on SMAPI 2.7 on SDV 1.3.28

Other installed mods :

AutoGate
Automate
CJB Item Spawner
Console Commands
DeluxeGrabber
SkipFishingMinigame
UI Info Suite

**Comment by Pathoschild** [comment]
How often does this happen? Can you make sure it doesn't happen when harvesting the crops normally? The mod essentially just harvests each crop as if you'd clicked on it yourself.

**Comment by compro01** [comment]
1. Current field shows 5 occurrences across 67 sprinklers.

2. Will test that next harvest.

**Comment by compro01** [comment]
This is a different bug than I thought it was.

When I tested for manual harvesting, the adjacent plant I thought was going showing as unharvested was actually getting harvested and showing it properly.

Looking at the game more closely and also looking at the image of my map on upload.farm, the problem plants aren't adjacent to the sprinklers, they're _on top of them_.  And they're actually not being harvested, because the plants can't be interacted with in any way.

![image of farm with problem plants circled](https://user-images.githubusercontent.com/2030521/47599035-05607f80-d963-11e8-8a5d-c045a23129d8.png)

It looks like the tractor is sometimes allowing seeds to be planted on squares where a sprinkler already is.  Then the game allows said plant to grow to maturity and produce fruit despite the sprinkler being there, not checking for the obstruction because there are already checks to prevent that from happening in the first place, but the tractor's planting function seems to either break or bypass those.

**Comment by Pathoschild** [comment]
Fixed in the next Tractor Mod release. Thanks for reporting it!
