### ISSUE TITLE
[Tractor Mod] Update idea: combine harvester

### ISSUE THREAD

**Issue by Nanogamer7** [Pathoschild/LookupAnything#345]
So the tractor is pretty cool, but with a large farm it still can get quite lengthy. My idea now a combine harvester: Upgrade of tractor, upgradeable just like coops and barns, has a 5x5 area and maybe drives a bit faster... etc.

**Comment by Pathoschild** [comment]
That's possible, but not sure if I'll add something like that in the foreseeable future since I'll be mainly focusing on SMAPI 3.0. In the meantime you can change the range and speed in the `config.json` though.

**Comment by Pathoschild** [comment]
I'll close this as _won't fix_ in the meantime, since I prefer to keep GitHub tasks for planned tasks. Thanks for the suggestion!
