### ISSUE TITLE
[Content Patcher] edit data not applying patches

### ISSUE THREAD

**Issue by Nanogamer7** [Pathoschild/LookupAnything#349]
I now modded on another mod and EditData doesn't work there either, patch is loaded and conditions are fulfilled, but not applied. There isn't any further error message in SMAPI log either... I included the other mod I tested on, it should add a new message to one of the lockers now (bottom row, last on first block)
[bathhouse_hot_spring_cp_1.1.0-alpha.1.zip](https://github.com/Pathoschild/StardewMods/files/2632478/bathhouse_hot_spring_cp_1.1.0-alpha.1.zip)

**Comment by Pathoschild** [comment]
@Nanogamer7 The content pack adds `BathHouse_MensLocker.5` to the `Strings/StringsFromMaps` asset, but the custom map isn't using it. I edited the map to use it and it appeared fine (tested in Content Patcher 1.5.3 and 1.6):
> ![](https://user-images.githubusercontent.com/230581/49313893-b4d6c780-f4b6-11e8-8c92-4c201bcde1f0.png)
