### ISSUE TITLE
[Chests Anywhere] Suggestion: Chests in tabs

### ISSUE THREAD

**Issue by nirewen** [Pathoschild/LookupAnything#368]
In my farm, I have lots of chests. Most of them are in a different color so I can differentiate them.
I use Chest Anywhere and separate them in categories, like Farm, Cavern, Drops, Fruits, Seeds, etc.
I would like to use Chests Anywhere better (even better)
If possible, the chests could be separated in tabs, different chests, different colors, and when you hover it you can see the name, and you can even scroll left and right and change the order. That would be nice.
I made a concept so you can see what I'm talking about (I'm not a designer)

![image](https://user-images.githubusercontent.com/8761479/51646134-7ad9ed00-1f5e-11e9-9157-30327d455080.png)

And if you hover you can see the name (in case of chests of the same color in the same category)

This is my concept, still need to find a way to include the chest options somehow (maybe inside the chest? If possible, so)

This is just an aesthetic suggestion, I find the way it is now very technical and I really have to click so much to switch between chests

**Comment by Pathoschild** [comment]
Thanks for the suggestion! That looks pretty nice, but it only works well for players with a small number of color-coded chests. I'd rather not maintain multiple UIs, so unfortunately I'll close this as _won't do_. To reduce clicking, an alternative is to use the hotkeys to quickly navigate through your chests (see [default values](https://github.com/Pathoschild/StardewMods/tree/develop/ChestsAnywhere#configure)).
