### ISSUE TITLE
[Automate] don't pull seeds from auto-grabber (if Auto-Grabber Mod is installed) or Junimo hut (if Better Junimos is installed)

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#370]
If [Deluxe Auto-Grabber](https://www.nexusmods.com/stardewvalley/mods/2462) is installed, Automate shouldn't pull seeds from auto-grabbers since that's how you enable Deluxe Auto-Grabber's auto-replant feature.

[Reported via Chucklefish forums](https://community.playstarbound.com/threads/looking-for-a-mod-that.147739/#post-3325761).

**Comment by Wiethoofd** [comment]
Having the ability to exclude items (with optional min/max quality) through the config would help a lot.

Example use case: Deluxe Auto-Grabber in coop, which also happens to contain an egg producing Dinosaur, it is [almost never worth it](https://stardewvalleywiki.com/Dinosaur_Egg#Artisan_Goods) turning that egg in to mayonaise, but will happen anyway if there is a mayonaise maker also attached to the Auto-Grabber.

A min- or maximum quality for excluded items would be: Iridium quality [Wool](https://stardewvalleywiki.com/Wool) from a rabbit in the aforementioned coop isn't maximizing the profit by turning it into cloth.

**Comment by Pathoschild** [comment]
@Wiethoofd Thanks for the suggestion! I have long-term plans to allow that kind of configurable filtering, but it's a bit involved so there's no timeline for that yet.

**Comment by Pathoschild** [comment]
Deluxe Auto-Grabber doesn't seem to have an auto-replant feature, but [Auto-Grabber Mod](https://www.nexusmods.com/stardewvalley/mods/2783) and [Better Junimos](https://www.nexusmods.com/stardewvalley/mods/2221) do.

**Comment by Pathoschild** [comment]
Done in `develop` for the next Automate release.
