### ISSUE TITLE
[Content Patcher] Allow arbitrary values in player configs

### ISSUE THREAD

**Issue by TehPers** [Pathoschild/LookupAnything#372]
Content Patcher's `ConfigSchema` should not restrict players to a limited set of allowed values. Instead, make `AllowedValues` optional, allow `Default` to be any arbitrary value if `AllowedValues` has not been defined, and allow players to enter arbitrary strings. A use case for this is to allow players to set arbirary names to items in the generated `config.json` instead of needing to edit `content.json` directly.

**Comment by Pathoschild** [comment]
Done in the upcoming Content Patcher 1.7. Thanks for the suggestion!
