### ISSUE TITLE
[Chests Anywhere] Issue with Shipping Bin and Farm Expansion

### ISSUE THREAD

**Issue by amalise** [Pathoschild/LookupAnything#373]
This is a consistent behavior issue with no log errors. I've trimmed things down to exactly these mods (plus CJB Item Spawner, so I could create a new game and create a few chests for testing).

It's possible the problem is on the Farm Expansion side; it's compatibility is listed as questionable, and there are a couple different unofficial patches. I tested this with the 1-huancz version, as the other is described as for the beta ONLY. My SMAPI and mods should all be up to date, but not into betas.

You typically request logs, so here's a link in case it helps: https://log.smapi.io/hSMDNu6w

Problem description:

It seems Chests Anywhere believes there is a Shipping Bin in the FarmExpansion area, even though there is not. Chests Anywhere doesn't seem convinced of this, however, because if you try to view FarmExpansion>Shipping Bin in Chests Anywhere you will be instantly redirected to the Farm>Shipping Bin chest. Because "FarmExpansion" comes after "Farm" alphabetically, this typically has the effect of making the "Next Category" hotkey take you back to Farm>Shipping Bin when it hits the FarmExpansion category.

This problem can be worked around by placing a chest in the Farm Expansion area, or at least in the FarmExpansion category, with a chest name which comes before "Shipping Bin" alphabetically. You would still have the bug effect if you used the Next Chest hotkey, but this at least renders the Next Category hotkey normally usable. Alternatively, turning off the Shipping Bin in the config gets around the problem.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the next Chests Anywhere release. Thanks for reporting it!
