### ISSUE TITLE
[Automate] Items Re-enter Cask

### ISSUE THREAD

**Issue by SwizzyStudios** [Pathoschild/LookupAnything#375]
**More of a Question than Issue.**
Issue: Item in Cask hits Iridium and goes back into cask at low quality (I cannot prove it hits Iridium quality as it is instant)
Setup:  Automate, CFR, CFAutomate, SwizzyDistillery-CFR
![image](https://user-images.githubusercontent.com/46543438/52763697-71362900-2fe2-11e9-8a6d-dc3ef71eb597.png)

So I wrote the Distillery mod and added in the ability to make different meads.  Using the CFR framework it should be coming out as an object with parentsheetid 459 but a different name and value.   I updated my mod to not change the name but it still happened.  I checked through the Automate code and couldn't find anything glaring to why this was happening with the Cask

I also went ahead and messed with the config after creating the mead to see some of the object information...
![image](https://user-images.githubusercontent.com/46543438/52763814-e570cc80-2fe2-11e9-9480-3e9d4da6ca8e.png)

I didn't see anything alarming in the SMAPI logs, except where I broke the object to try and get some information.  https://log.smapi.io/L2wLtRVP

Any thoughts or suggestions short of re-writing from ground up?

**Comment by Pathoschild** [comment]
I suspect the issue is in CFR, but I'll take a look to make sure. Can you post a zip of your `Mods` folder and [save files](https://stardewvalleywiki.com/Saves), and steps to reproduce the issue (e.g. a specific item to put in the cask chest)?

**Comment by SwizzyStudios** [comment]
I will do this when I get home.

**Comment by SwizzyStudios** [comment]
[Mods.zip](https://github.com/Pathoschild/StardewMods/files/2867433/Mods.zip)
[Swizzy_206771246.zip](https://github.com/Pathoschild/StardewMods/files/2867434/Swizzy_206771246.zip)

Steps:

1. Spawn in Distillery.
2. Spawn in chest/cask.
3. Place Distillery -> Cask -> Chest within Cellar.
4. Spawn in Any Honey type, I usually do the poppy.
5. Place Honey in Distillery. 10hrs to produce "custom mead from CFR object"
6. It goes into Cask but once it would hit iridium quality seems to reset or is resent back into cask from chest.

**Comment by Pathoschild** [comment]
@SwizzyStudios Yep, this is an issue with Custom Farming Redux. I reported it to the CFR developer; see Platonymous/Stardew-Valley-Mods#46 for more info.

**Comment by SwizzyStudios** [comment]
thanks for looking into it
