### ISSUE TITLE
[Lookup Anything] agriculturalist bug

### ISSUE THREAD

**Issue by Traehgniw** [Pathoschild/LookupAnything#418]
looking up seeds in the inventory doesn't take into account agriculturalist's effect on grow time adn does not give an indication that it isn't taking it into account

looking up planted seeds correctly applies the growth speed increase but thats not helpful if you're trying to figure out, on fall 16th in a Seeds are Rare playthrough, if you should plant those pumpkins or restart the day and *not* put your current only pumpkin into the upgraded seed maker

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Lookup Anything 1.22. Thanks for reporting it!
