### ISSUE TITLE
[Lookup Anything] Planted winter seeds fail at math

### ISSUE THREAD

**Issue by Traehgniw** [Pathoschild/LookupAnything#424]
![image](https://user-images.githubusercontent.com/42482668/59142943-cf679b80-8a19-11e9-96d7-b6db374b097d.png)

winter seeds planted without the recipe (via seed maker to get them), on winter 22, claiming they will be harvested on winter 28 (yes) in 118 days (uh...no...try 6)
it also calls it a Winter Root, which has a dedicated crop in my game due to Forage to Farm which I can't use due to Seeds are Rare.

[Madeline_216200980.zip](https://github.com/Pathoschild/StardewMods/files/3268261/Madeline_216200980.zip)
should wake up on winter 22 with Winter Roots ready to harvest. has uh...MANY MANY mods installed, most notably SVE with IF2R, jsonassets Forage to Farm, Fruits and Veggies, Six Plantable Crops For Winter, Bonster's Fruit and Veg, Bonster's Trees, More Food, More Recipes, Even More Recipes, More Trees, Mizu's Flowers, Jewelcraft and Artisan Valley, and Animal Husbandry. Meat recipes included. 
So if you want to check on that save you'll need...at least those maybe more, sorry, I run 211 mods.

**Comment by Pathoschild** [comment]
Fixed in SMAPI 3.0 via https://github.com/Pathoschild/SMAPI/commit/adeeabd0f1dd1c564cc6f7cced330f30043242bf. Thanks for reporting it!
