### ISSUE TITLE
[Content Patcher] Rectangle Tokens

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/LookupAnything#425]
Allow tokens to supply values for `Rectangle`s. This would allow simplifying some mods with dynamic tokens, and allow for things like Json Assets coordinate tokens (for applying textures to JA objects).

**Comment by Pathoschild** [comment]
@spacechase0 To clarify, are you suggesting a token which returns a `Rectangle` instance:
```js
"FromArea": "{{SourceArea}}"
```
Or letting you specify rectangle arguments using tokens:
```js
"FromArea": { "X": "{{SourceX}}", "Y": "{{SourceY}}", "Width": 16, "Height": 16 }
```

**Comment by spacechase0** [comment]
Either would work for me (so long as it is possible from the perspective of a mod providing tokens). I'm not sure what would be preferred from a content pack creator's perspective.

**Comment by Pathoschild** [comment]
The first would break a core assumption in the Content Patcher design and involve a major rewrite; the second is simple to implement. So let's go for the second one. ;)
