### ISSUE TITLE
[Tractor Mod] Trees always drop from the right no matter where the tractor is

### ISSUE THREAD

**Issue by klaurence** [Pathoschild/LookupAnything#433]
With the Tractor and the axe selected, trees drop to the right even when the tractor cut the tree from the right, which should make the tree drop to the left.

**Comment by klaurence** [comment]
With all due respect, I think you may have misunderstood my report and I want to make it clearer. It's more of "fixing an unintended problem, the problem being that trees always drop to the right even if cut from the left with the tractor" and less of "adding an intended feature, the feature being that trees should drop to the left when cut from the right with the tractor". I totally mean no offense.

**Comment by Pathoschild** [comment]
The axe is applied to each tile as if the player were right on top it, and trees always drop to the right in that case. That's intended behavior, but I agree that radial tool effects would be better (thus `enhancement`). The label doesn't much difference though.

**Comment by Pathoschild** [comment]
Done in the upcoming Tractor Mod 4.9. Thanks for the suggestion!
