### ISSUE TITLE
[Fast Animations] disabling eat/drink confirmation doesn't work unless eat/drink speed is set to one

### ISSUE THREAD

**Issue by klaurence** [Pathoschild/LookupAnything#435]

**Comment by Pathoschild** [comment]
[Also reported on Nexus](https://www.nexusmods.com/stardewvalley/mods/1089/?tab=bugs&issue_id=432021).

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Fast Animations 1.7.3.
