### ISSUE TITLE
[Tractor Mod] Add "chop big crops" feature for axe

### ISSUE THREAD

**Issue by klaurence** [Pathoschild/LookupAnything#456]

**Comment by Pathoschild** [comment]
@KLaurence Do you have an example save with giant crops to test with?

**Comment by klaurence** [comment]
@Pathoschild Would a test world with large pumpkins suffice?

**Comment by klaurence** [comment]
If so, a download link is [here](http://www.mediafire.com/file/q2vurzxzvk4vhi0/Test_226990910.zip/file).

**Comment by Pathoschild** [comment]
Done in the upcoming Tractor Mod 4.9. Thanks for the suggestion!
