### ISSUE TITLE
[Automate]/[Chests Anywhere] Option to allow/deny Workbench to pull from a chest, with configurable default

### ISSUE THREAD

**Issue by nuker1110** [Pathoschild/LookupAnything#467]
I'd love to be able to set my Smelter array and Wood chipper suite to both connect to the Workbench, but not each other. As it stands, this results in very limited options on where to place/arrange those two layouts.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! That's a long-term goal, but doing it in a way that doesn't affect performance isn't trivial. See #307 and #61 for more info.
