### ISSUE TITLE
[Lookup Anything] update for Json Assets' limit break change

### ISSUE THREAD

**Issue by Traehgniw** [Pathoschild/LookupAnything#473]
It crashes the mod (not the game, just massive amounts of redtext) on looking up certain JA crops. All crops of affected species are affected.

Have a mods folder + save to replicate, the Automatoes that the error was constantly occuring on are the grey plants like the two under the scarecrow.

https://drive.google.com/file/d/1bA_S4y1sMH5jrYou7TLHN5bN2Vf0t8sT/view?usp=sharing

**Comment by Traehgniw** [comment]
You can probably also spawn in a bunch of JA trees of lots of types and replicate with that, I have loads and loads of tree mods installed too.

**Comment by Traehgniw** [comment]
Whoops, that's not automatoes, that's some kind of pokecrop. I didn't know until it had grown more.

Point is it's grey and it's breaking Lookup Anything.

**Comment by Pathoschild** [comment]
That's an issue in Json Assets.

Lookup Anything calls the Json Assets API to get the texture and source area for a crop (the source area contains the sprites for each phase of growth). Then it gets the source area for the current sprite from `crop.getSourceRect`, but Json Assets doesn't adjust that method for its modified logic which results in the area being past the end of its texture.

I reported the issue to spacechase0 so they can take a look.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Lookup Anything 1.23.1 (by calling a separate API method for crops).
