### ISSUE TITLE
[Content Patcher] Pine tree seasonal changes not applying in desert

### ISSUE THREAD

**Issue by minervamaga** [Pathoschild/LookupAnything#474]
Problem: https://i.imgur.com/ApNzaxF.png (Pine trees outside the desert are fine)
Log with just CP and Eernies: https://smapi.io/log/jzdFDrnL

Reported by a user in #modding
Patch summary shows it should be applying, but as you can see, it's not.

**Comment by Pathoschild** [comment]
@minervamaga Can you post a save + minimal `Mods` folder to reproduce it?

**Comment by Pathoschild** [comment]
@minervamaga Desert trees use summer textures in all seasons, and pine trees have no summer texture so they use spring instead. So essentially you need to target `TerrainFeatures/tree3_spring` in all seasons to correctly change desert trees.
