### ISSUE TITLE
Time Speed Mod

### ISSUE THREAD

**Issue by FarmingApple** [Pathoschild/LookupAnything#485]
I'm sorry to ask you questions in a place like this. Numbers no longer blink when they stop. Is it new version? Or am I wrong? I can't tell if it's stopped or not. If it's new, I'd like it to blink again. I would like to ask you a sincere favor.

**Comment by Pathoschild** [comment]
Hi! You can report TimeSpeed issues to the [repository for TimeSpeed](https://github.com/cantorsdust/StardewMods) instead.
