### ISSUE TITLE
[Data Layers] Add layer to indicate tilled but not-yet planted tiles

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Pathoschild/LookupAnything#495]
It would be useful to have a layer to indicate tiles which are tilled but not-yet planted.

**Comment by Pathoschild** [comment]
You can see missing crops in the current crop layers, so not sure we need a dedicated layer:
> ![](https://user-images.githubusercontent.com/230581/71643658-3dabce00-2c8a-11ea-9195-8cbb86374558.png)
> ![](https://user-images.githubusercontent.com/230581/71643683-6a5fe580-2c8a-11ea-9e13-803bfeaa4d14.png)

**Comment by Drachenkaetzchen** [comment]
Yes, that's correct. However, it's pretty hard to see (especially in non-rectangular fields) and right now I'm not sure if what you showed in the screenshot also applies to non-tilled soil.

**Comment by Pathoschild** [comment]
Yep, it does. Crop layers highlight crops in red or green, so any missing crops will appear as a hole in the color overlay.

**Comment by Drachenkaetzchen** [comment]
Yes, but the hole in the color overlay is also present on non-tilled soil.

The question to be answered is: "Is there any tilled soil where I forgot to plant stuff?"

![image](https://user-images.githubusercontent.com/162974/71643846-0f94b100-2cbf-11ea-8554-5eb9f77e9ab0.png)

**Comment by Drachenkaetzchen** [comment]
Note that it's only a quality of life thing, and shouldn't be high priority. I might implement it and send it as PR.

**Comment by Drachenkaetzchen** [comment]
I did an initial implementation on the tillable layer. What do you think? Does that make sense?
![image](https://user-images.githubusercontent.com/162974/71680870-85664e80-2d8b-11ea-9b59-a699d7d97bb2.png)

**Comment by Pathoschild** [comment]
Thanks! Added in the next Data Layer update.

I made a few tweaks:
> ![image](https://user-images.githubusercontent.com/230581/73114687-ce24a980-3eea-11ea-8b29-d759a76d6f10.png)
