### ISSUE TITLE
Improper alpha channel declaration for Color | CommandHandler.cs

### ISSUE THREAD

**Issue by cosmicdreams** [Pathoschild/LookupAnything#496]
On line 638 of CommandHandler.cs (in ContentPatcher) you declare the alpha channel of a Color to be a. The proper name of the property is alpha.

Fix:
use this for line 638:

```alpha: pixel.A```

**Comment by Pathoschild** [comment]
The names are inconsistent between Linux/Mac (`alpha`) and Windows (`a`). The compiled version will work fine in both, but I removed the names to avoid compile errors on Linux/Mac. Thanks for reporting it!

**Comment by cosmicdreams** [comment]
No problem. Went through the process of setting up a local environment so I could provided a PR.  Do you mind if I move the comment to above the declaration?

**Comment by Pathoschild** [comment]
It's a bit odd here for a multiline statement, but I use comments on their own line to group blocks of code and on the side for a note about a specific line.
