### ISSUE TITLE
[Automate] Can't seem to connect a chest to a Large Shed

### ISSUE THREAD

**Issue by cosmicdreams** [Pathoschild/LookupAnything#503]
In #61 transport pipes were added.  The issues original description references being able to connect the output of a barn to in the input of a shed.  I tried to do something similar (connecting a chest to a shed using a connecting path).  That isn't working for me and I don't know why.

What I'm trying to do:
I added "Cobblestone Path" to the list of Connectors
I'm using that Cobblestone path to connect a Large Shed filled with casks to a chest.
I also connect that chest with another (Small) shed filled with Kegs.

Now I almost think it isn't the fault of the core game because of how Barns behave differently that Sheds.  With a Barn, I can make a Cobblestone Path occupy the square inside the barn that immediately leads outside.  In the Shed I can't seem to place a path in that respective square.  

So maybe this doesn't work because the circuit can't be completed?

**Comment by Pathoschild** [comment]
Transport pipes aren't implemented yet. (You're probably thinking of connectors, a much simpler feature which also extends connections.)
