### ISSUE TITLE
[Automate] - Add ability to make a chest a priority input

### ISSUE THREAD

**Issue by MadaraUchiha** [Pathoschild/LookupAnything#509]
It is currently possible, using Chests Everywhere, to define a chest as priority output (i.e. "Put items in this chest first"), but no way to define a chest as priority input (i.e. "Take items from this chest first").

This is a request to add that feature.

![image](https://user-images.githubusercontent.com/1188951/73104964-5d888780-3f00-11ea-8b1d-832d53f5f7e1.png)

I am willing to put up a pull request for this (currently reading the code), advice on how to implement this and where I should focus my reading would be greatly appreciated.

**Comment by Pathoschild** [comment]
Thanks! Added via #510 for the next Chests Anywhere and Lookup Anything updates.
