### ISSUE TITLE
[Content Patcher] Dialogue data patches are applied before 'when' conditions are evaluated

### ISSUE THREAD

**Issue by mus-candidus** [Pathoschild/LookupAnything#536]
This is hard to describe properly so I attached a mod to reproduce the issue.
Caroline tells the correct day of week only on the day the game was loaded. Starting from the next day she lives in the past.

[DialogueIssue.zip](https://github.com/Pathoschild/StardewMods/files/4365683/DialogueIssue.zip)

**Comment by Pathoschild** [comment]
It seems to work fine for me:
> ![image](https://user-images.githubusercontent.com/230581/77259679-9cfdf680-6c59-11ea-805e-be32fcc72b41.png)
> ![image](https://user-images.githubusercontent.com/230581/77259692-b69f3e00-6c59-11ea-9928-bdf4ac344c68.png)

Does it work if you remove all mods except Content Patcher and that content pack?

**Comment by mus-candidus** [comment]
Thanks for your quick response! Unfortunately removing all other mods doesn't work.
Here is a picture and a detailed log:

![thursday](https://user-images.githubusercontent.com/30182778/77261363-43fc8580-6c8e-11ea-9fd0-8cbca4fbd8f1.png)

https://smapi.io/log/5cf9e0ac4f614e9e88add12c1c0575bd

Maybe a Linux-specific issue?

**Comment by Pathoschild** [comment]
Yep, it's an issue on Linux/Mac only. It's fixed in the next SMAPI update now; thanks for reporting it!
