### ISSUE TITLE
[Fast Animations] Support fractional playback rates

### ISSUE THREAD

**Issue by seraku24** [Pathoschild/LookupAnything#541]
I am finding that 200% is a little too fast for tool and weapon usage.  However, specifying a real number (e.g. 1.5 for 150% speed) results in an error parsing the configuration as the mod expects an integer.

Would it be possible to support non-integral values to fine-tune the playback rate?

**Edit:** Taking a quick look at the code, it appears this mod works by calling `Update` additional times per normal time step.  It makes sense why an integer value is used.  To support a rational value, it should only be necessary to keep an internal counter that increments by the requested rate each time step.  This would mean for 1.5x, the extra `Update` happens every other normal time step.  When I get a local build environment running, I will try out my approach and submit a PR should it work.

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming Fast Animations 1.8.
