### ISSUE TITLE
Update all mods for SMAPI 1.9

### ISSUE THREAD

**Issue by sickpuppy0x2a** [Pathoschild/LookupAnything#56]
´Not working with SMAPI 1.9 and Stardew Valley beta, otherwise really great mod

**Comment by Pathoschild** [comment]
I'll start updating the mods soon; I've been focused on making SMAPI itself compatible first. :)

**Comment by sickpuppy0x2a** [comment]
Thanks for your work :)

**Comment by Pathoschild** [comment]
I just released beta versions for all the mods to support Stardew Valley 1.2:

* [Chests Anywhere 1.9-beta](http://community.playstarbound.com/threads/smapi-chests-anywhere.122603/page-6#post-3118393)
* [Debug Mode 1.4-beta](http://community.playstarbound.com/threads/debug-mode.126551/#post-3118396)
* [Lookup Anything 1.11-beta](http://community.playstarbound.com/threads/smapi-lookup-anything.122929/page-15#post-3118379)
* [Skip Intro 1.5-beta](http://community.playstarbound.com/threads/smapi-skip-intro.123673/#post-3118404)

**Comment by Pathoschild** [comment]
All mods are now updated for Stardew Valley 1.2. I'll release another update if they break something in a future beta, but otherwise this is done.
