### ISSUE TITLE
[Lookup Anything] add reverse recipe lookup

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#562]
Looking up an item should show any recipes that produce it.

Proposed in the [Nexus comments for Lookup Anything](https://www.nexusmods.com/stardewvalley/mods/541/?tab=posts&jump_to_comment=83892688) (2020-08-04).

**Comment by Smugger21** [comment]
As I just posted on the Nexus. No rush.
If I am pointed in the right direction, I may be able to help with it, I know just enough c# to be dangerous.
I need to get better at it, also, I need to start building some sort of Github portfolio.

**Comment by Pathoschild** [comment]
Sure, pull requests are always welcome! The main changes would be in [`ItemSubject.GetData`](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/Framework/Subjects/ItemSubject.cs#L87), but we might need a few other changes for this. Feel free to come chat in [#making-mods on Discord](https://smapi.io/community#Discord) if you're interested; we're happy to answer questions from new modders there, and I can help with any questions about the mod code.

**Comment by Pathoschild** [comment]
Done via #609 for the upcoming Lookup Anything 1.33.
