### ISSUE TITLE
[Content Patcher]Can't set images for different languages

### ISSUE THREAD

**Issue by DL0101** [Pathoschild/LookupAnything#564]
I wanted to add images for different languages, but the code didn't work and the console didn't report an error.
{
    "Format":"1.16.0", 
    "Enabled":"true", 
    "ConfigSchema":{
        "Interface":{
            "AllowValues":"true,false", "Default":"true"
        },  
    },
{
     "Action":"EditImage",
     "Target":"Minigames/TitleButtons",
     "FromFile":"interface/TitleButtons.png",
     "PatchMode":"Overlay",
     "When":
            {
               "Interface":"true",
            }
    },
{
     "Action":"EditImage",
     "Target":"Minigames/TitleButtons.zh-CN",
     "FromFile":"interface/TitleButtons.zh-CN.png",
     "When":
            {
                "Language": "zh",
            }
    },
}

**Comment by Pathoschild** [comment]
Hi! The language isn't part of the asset name, and your patches apply in all languages by default. You can target specific languages using the language token instead.

The easiest approach is use `{{language}}` in the `FromFile` field, like `TitleButtons.{{language}}.png`. Then just create files like `TitleButtons.zh.png`, and they'll be applied automatically for the language if they exist:

```js
{
   "Format": "1.16.0",
   "ConfigSchema": {
      "Interface": {
         "AllowValues": "true, false",
         "Default": "true"
      },
   },
   "Changes": [
      {
         "Action": "EditImage",
         "Target": "Minigames/TitleButtons",
         "FromFile": "interface/TitleButtons.{{language}}.png",
         "PatchMode": "Overlay",
         "When": {
            "Interface": "true",
            "HasFile:{{FromFile}}": "true"
         }
      },
      {
         "Action": "EditImage",
         "Target": "Minigames/TitleButtons",
         "FromFile": "interface/TitleButtons.png",
         "PatchMode": "Overlay",
         "When": {
            "Interface": "true",
            "HasFile:interface/TitleButtons.{{language}}.png": "false"
         }
      }
   ]
}
```

See [_common fields_ in the author guide](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-guide.md#common-fields) and [the language token](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-tokens-guide.md#metadata) for more info, and feel free to [come ask on Discord](https://smapi.io/community#Discord) if you have any questions!

**Comment by DL0101** [comment]
Thanks a lot!!!
