### ISSUE TITLE
[Content Patcher]Mod replaced images can‘t be fully loaded each time I enter the game

### ISSUE THREAD

**Issue by DL0101** [Pathoschild/LookupAnything#565]
I'm here for the incompetent. I have an interface to beautify mod. But every time I enter the game, the buttons on the start interface (new, load, co-op...) still display the original version, but after I load the archive and return, After I return, it can be displayed normally.. How can I solve this problem?

**Comment by Pathoschild** [comment]
Hi! Come ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll help you get it working. (GitHub issues are only used to track development work, since most modders who could help don't watch here.)

**Comment by DL0101** [comment]
> 嗨！快来[Stardew Valley Discord上的＃making-mods中询问](https://smapi.io/community#Discord)，我们将帮助您使其正常工作。（GitHub问题仅用于跟踪开发工作，因为大多数可以帮助的修改者不在此处关注。）

thank you!
