### ISSUE TITLE
[Content Patcher] Image not correctly edited

### ISSUE THREAD

**Issue by Territorys** [Pathoschild/LookupAnything#566]
I found, probably, a little bug. The door’s image wasn’t correctly edited.

For better proof I've taken the original image of the three doors and I've colored each opening phase with white, red, blue, and green.

Original image:
![doors - original](https://user-images.githubusercontent.com/7595891/91346119-a5e28d80-e7e0-11ea-9f8a-3179d4b8bf59.png)
Edited image:
![doors](https://user-images.githubusercontent.com/7595891/91346132-ab3fd800-e7e0-11ea-9a62-63557e886727.png)

As you can see from the 3 gif below, all of the 3 doors at the start aren’t completely blank as they should be, but there are residues of the original image.

<img src="https://user-images.githubusercontent.com/7595891/91346297-ecd08300-e7e0-11ea-844d-1af40803f7a2.gif" data-canonical-src="https://user-images.githubusercontent.com/7595891/91346297-ecd08300-e7e0-11ea-844d-1af40803f7a2.gif" width="204" height="167" /> <img src="https://user-images.githubusercontent.com/7595891/91347829-37eb9580-e7e3-11ea-90ec-9439c6710219.gif" data-canonical-src="https://user-images.githubusercontent.com/7595891/91347829-37eb9580-e7e3-11ea-90ec-9439c6710219.gif" width="204" height="167" /> <img src="https://user-images.githubusercontent.com/7595891/91347931-5b164500-e7e3-11ea-8577-eb01d4de77ba.gif" data-canonical-src="https://user-images.githubusercontent.com/7595891/91347931-5b164500-e7e3-11ea-8577-eb01d4de77ba.gif" width="204" height="167" />

I have tried with `"PatchMode": "Replace"` and `"PatchMode": "Overlay"` but the results don't change. 
Down below, I put the list of the mod loaded to make the example above and the content of my 3 json.

Game and Mods versions:
```
Stardew Valley 1.4.5
SMAPI 3.6.2
Content Patcher 1.17.1
Save Backup 3.6.2
Test Mood for ContentPatcher 0.1.0
```
My mod files:
- manifest.json
```
{
    "Name": "Test Mood for ContentPatcher",
    "Author": "Territory91",
    "Description": "It's a test mod for ContentPatcher",
    "Version": "0.1",
    "MinimumApiVersion": "3.2.0",
    "UniqueID": "territory.modtest",
    "ContentPackFor": {
        "UniqueID": "Pathoschild.ContentPatcher",
        "MinimumVersion": "1.12.0"
    }
}
```
- content.json
```
{
     "Format": "1.17.0",
     "ConfigSchema": {
         "TerrytoryDoorsEnabled": {
             "AllowValues": "true, false",
             "Default": "true"
         }
     },
     "Changes": [{
         "Action": "EditImage",
         "Target": "LooseSprites/Cursors",
         "FromFile": "tilesheetassets/doors.png",
         "PatchMode": "Replace",
         "FromArea": { "X": 0, "Y": 0, "Width": 180, "Height": 47 },
         "ToArea": { "X": 512, "Y": 145, "Width": 180, "Height": 47 },
         "When": { "TerrytoryDoorsEnabled": "true"}
     }]
 }
```
- config.json
```
{ "TerrytoryDoorsEnabled": "true" }
```
Zip of my example mod.
[[CP] TestMood.zip](https://github.com/Pathoschild/StardewMods/files/5132700/CP.TestMood.zip)

**Comment by Pathoschild** [comment]
Hi! The issue is that doors have two parts:
* The opening sprites in `LooseSprites\Cursors`, which you edited:
  > ![](https://user-images.githubusercontent.com/230581/91364001-d2d87580-e7cb-11ea-8307-ffd633a55671.png)
* And the fully-closed sprites defined by the `Doors` [map property](https://stardewvalleywiki.com/Modding:Maps#Known_properties), which in this case is set to these sprites in the `Maps/townInterior` tilesheet:
   > ![](https://user-images.githubusercontent.com/230581/91363477-b4be4580-e7ca-11ea-814b-09a1235371b5.png)

A quick test shows that editing both places does work:
> ![image](https://user-images.githubusercontent.com/230581/91363730-3c0bb900-e7cb-11ea-83b7-b7df7630ccaf.png)
