### ISSUE TITLE
How to get the project up and running on Visual Studio / Mac? 

### ISSUE THREAD

**Issue by osheroff** [Pathoschild/LookupAnything#572]
My goddaughter and I are using your source as a starting point in learning to code. 
We are trying to modify the tractor-mod and the noclipmode mod in order to create a flying Air Bison character.  

Having trouble getting the project going under Visual Studio.  If I futz with the project options enough I can get it compiling, but I don't see any "run" configurations at all.  Is there something I'm missing?  I'm opening up `Pathoschild.Stardew.sln` in Visual Studio. 

Thanks much, 
Ben & Violet

**Comment by Pathoschild** [comment]
Hi! The mods should be copied into your game's `Mods` folder automatically when you rebuild the projects. If you already have SMAPI installed, just launch the game as usual and your freshly compiled mods should load.

I'm not sure why launching directly from Visual Studio isn't working for you though, and you shouldn't need to change any project options to compile on MacOS. If you come ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord), we can help you get it all working smoothly. (Feel free to ping me there if you don't get an answer!)
