### ISSUE TITLE
Support mod translations

### ISSUE THREAD

**Issue by bruceCzK** [Pathoschild/LookupAnything#58]
Is it possible to use description texts of other language such as Chinese?

**Comment by Pathoschild** [comment]
Hi @bruceCzK. I do want to translate Lookup Anything, but it'll be a lot of work. I'll look into it sometime after Stardew Valley 1.2 is released. :)

**Comment by vizv** [comment]
@Pathoschild I'm planning to translate Lookup Anything to Chinese, any suggestion / guide for how should I do it?

**Comment by Pathoschild** [comment]
It's not really possible yet. I'll look into translating all my mods (including Lookup Anything) once Stardew Valley 1.2 and SMAPI 2.0 (which has some features that will make it easier) are released. :)

**Comment by Pathoschild** [comment]
SMAPI 1.14 will add a mod translation API (see pathoschild/SMAPI#296), and I'll add translation support for all my mods soon after.

**Comment by Pathoschild** [comment]
My mods can now be translated into any language supported by the game. 🎉 

## How to translate
Here's how to translate one of my mods:

1. Install [SMAPI 1.14+](https://github.com/Pathoschild/SMAPI/releases).
2. Install the preview version (see below) of the mod to translate.
2. Copy `default.json` into a new file with the right name:

   language | file name
   -------- | ---------
   Chinese  | `zh.json`
   German   | `de.json`
   Japanese | `ja.json`
   Portuguese | `pt.json`
   Spanish | `es.json`

3. Translate the second part on each line:
   ```
   "example-key": "some text here"
                   ^-- translate this
   ```
   Don't change the quote characters, and don't translate the text inside `{{these brackets}}`.
4. Launch the game to try your translations.  
   _You can edit translations without restarting the game; just type `reload_i18n` in the SMAPI console to reload the translation files._

Post translations here or send them to me privately. :)

## Current status
Translations so far:

&nbsp;     | Chests Anywhere | Debug Mode | Lookup Anything | thanks to
------     | --------------- | ---------- | --------------- | ---------
Chinese    | ✓ [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/zh.json) | ✓ [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/zh.json) | ✓ [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/zh.json) | yuwenlan
German     | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/de.json) | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/de.json) | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/de.json) | Sasara
Japanese   | 
Portuguese | 
Spanish    | 

## Preview versions
Here are preview builds of the upcoming releases, with translation support included:

- [ChestsAnywhere 1.11-prerelease.4.zip](https://github.com/Pathoschild/StardewMods/files/1049352/ChestsAnywhere.1.11-prerelease.4.zip)
- [DebugMode 1.6-prerelease.4.zip](https://github.com/Pathoschild/StardewMods/files/1049353/DebugMode.1.6-prerelease.4.zip)
- [LookupAnything 1.14-prerelease.4.zip](https://github.com/Pathoschild/StardewMods/files/1049354/LookupAnything.1.14-prerelease.4.zip)

**Comment by Pathoschild** [comment]
@bruceCzK @vizv See above if you're interested in providing Chinese translations. :)

**Comment by Pathoschild** [comment]
Translations so far:

&nbsp;     | Chests Anywhere | Debug Mode | Lookup Anything
------     | --------------- | ---------- | ---------------
Chinese    |                 |            | ✓ [zh.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/zh.json)
German     | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/i18n/de.json) | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/DebugMode/i18n/de.json) | ✓ [de.json](https://github.com/Pathoschild/StardewMods/blob/develop/LookupAnything/i18n/de.json)
Japanese   | 
Portuguese | 
Spanish    |

**Comment by Pathoschild** [comment]
Closed for release. Any further translations can be added in future versions.
