### ISSUE TITLE
[Content Patcher] Old pack no longer working (missing vanilla tilesheets)

### ISSUE THREAD

**Issue by notevenamouse** [Pathoschild/LookupAnything#582]
[There's a CP 1.3 pack here](https://community.playstarbound.com/threads/migrating-xnb-mods-to-content-patcher-packs.141577/page-9#post-3275665) that works in CP 1.19.0 for 1.4.5 [log](https://smapi.io/log/09bf904544fd4036acb315f459f503a9) , but not in latest build for 1.5 [log](https://smapi.io/log/f2b372c14048482f9e21ac596370f5ed).

**Comment by Pathoschild** [comment]
@hatrat That was an early unofficial update, before Content Patcher fully supported map replacements, so it loads the map files as XNB files. There seems to be a new quirk in Stardew Valley 1.5 which breaks tilesheet paths when they're loaded from an `.xnb` file in a mod folder. I released a new unofficial update which just unpacks the map files into `.tmx` (and simplifies the content pack using other newer Content Patcher features).

**Comment by notevenamouse** [comment]
Yeah, I ran into the same thing with some other packs that use xnb files. Should all of them just be updated to use unpacked files?

(PS, thank you for looking into it!)

**Comment by Pathoschild** [comment]
@hatrat It seems Stardew Valley 1.5 changed the underlying xTile map library to normalize tilesheet paths directly on load. In particular, the relative map asset path is prepended to the tilesheet path. I'll have to run some experiments to see how consistently this happens, and whether SMAPI can automatically correct it where applicable.

**Comment by Pathoschild** [comment]
Done in the upcoming SMAPI 3.9, which will retroactively fix content packs affected by the game change.
