### ISSUE TITLE
[Lookup Anything] Show crop data when looking at seed

### ISSUE THREAD

**Issue by mathuin** [Pathoschild/LookupAnything#59]
Sometimes I will be looking at seeds in Pierre's store but I won't know whether or not I need that particular crop for a quest or recipe.  It would be nice to look at say potato seeds and see whether or not I have completed the achievements for potatoes.  Etc.

**Comment by Pathoschild** [comment]
@mathuin I have a prototype in `develop` which lets you look up the crop from the seed page by clicking a link:
![](https://cloud.githubusercontent.com/assets/230581/24782096/094f7e72-1b12-11e7-9400-d366a585d71b.png)

What do you think of that approach? I think trying to fit the crop info on the seed page might be too messy and confusing, but this lets you quickly access the information while keeping it separate.

**Comment by Pathoschild** [comment]
Released with Lookup Anything 1.12. :)
