### ISSUE TITLE
[Content Patcher] Special order board won't show

### ISSUE THREAD

**Issue by Warilized** [Pathoschild/LookupAnything#590]
Using "Load" action reverts the SO board to nothing.

It still had the ! New Quest icon, amusingly.

**Comment by Pathoschild** [comment]
@Warilized Can you attach a zip of the content pack with that issue?

**Comment by Pathoschild** [comment]
I'll close this ticket since I don't have the content pack to reproduce it, but it's probably caused by Pathoschild/SMAPI#751.
