### ISSUE TITLE
[Content Patcher] [Request] Add condition that checks for NPC locations

### ISSUE THREAD

**Issue by ViolentQuiche** [Pathoschild/LookupAnything#596]

**Comment by Pathoschild** [comment]
Hi! Unfortunately that isn't possible currently. Patches can update at three points: when a new day starts (default), when the player warps, and when the in-game clock changes. NPCs can change location at any time between those points, so patches would not be updated consistently.

Content Patcher is gradually migrating towards near-real-time updates though, so tokens like that may be possible in upcoming versions.
