### ISSUE TITLE
Quality and Deluxe Fertilizer Lookups are Switched

### ISSUE THREAD

**Issue by LonerAoshi** [Pathoschild/LookupAnything#598]
When looking up fertilized tiles, Quality Fertilizer shows as Deluxe Fertilizer and vice-versa. I can see it here:

>  HoeDirt.fertilizerLowQuality => GameI18n.GetObjectName(368), // Basic Fertilizer
                    HoeDirt.fertilizerHighQuality => GameI18n.GetObjectName(919), // Deluxe Fertilizer
                    HoeDirt.fertilizerDeluxeQuality => GameI18n.GetObjectName(369), // Quality Fertilizer

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Lookup Anything 1.31.1. Thanks for reporting it!
