### ISSUE TITLE
[ChestsAnywhere] Fix typo in readme "DisableInLocations" -> "DisabledInLocations"

### ISSUE THREAD

**Issue by cofiem** [Pathoschild/LookupAnything#600]
The ChestsAnywhere [Readme](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/README.md) has an incorrect config file key name.

"DisableInLocations" should be "DisabledInLocations" according to the [code](https://github.com/Pathoschild/StardewMods/blob/develop/ChestsAnywhere/Framework/ModConfig.cs#L27).

**Comment by Pathoschild** [comment]
Fixed. Thanks for reporting it!
