### ISSUE TITLE
[Content Patcher] Investigate lag skips with Diverse Stardew Valley

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/LookupAnything#601]
When [Diverse Stardew Valley](https://www.nexusmods.com/stardewvalley/mods/4079) is installed, some players experience lag skips when the in-game clock time changes.

**Comment by Pathoschild** [comment]
This is apparently a common issue with DSV, but only one user actually reported it so far.

[quinnnethq](https://www.nexusmods.com/stardewvalley/users/59769606) on MacOS experiences lag skips every time `OnTimeChange` fires (and only then). This happens even with other mods removed ([see log](https://smapi.io/log/nPgH3MkV)), and the [game's memory usage is at 2.95GB](https://imgur.com/a/bMetg2x) when it happens. The `TRACE` logs show very frequent asset invalidations for NPC portraits/sprites.

**Comment by Pathoschild** [comment]
Fixed with optimizations in Content Patcher 1.20, and I haven't received any further reports of this happening after the update.

**Comment by ThreepQuest64** [comment]
> Fixed with optimizations in Content Patcher 1.20, and I haven't received any further reports of this happening after the update.

Unfortunately this version is not available/working for Android and thus the issue continues to exist on Android platforms with DSV installed :(

**Comment by Pathoschild** [comment]
Yep. Hopefully Android players will get the latest game version soon to fix that.
