### ISSUE TITLE
[Content Patcher] Suggestion: Assigning type to config.

### ISSUE THREAD

**Issue by Warilized** [Pathoschild/LookupAnything#602]
To better integrate with Generic Mod Config menu, the mods needs to tell what type of data is being provided.

Assigning type to player config will make things easier and neater for player/modder to set it to their preferences. And provide a wide range of config possibilities just like GMCM dependant SMAPI mod.

Example:
```
"Integer Type setting": {
    "AllowValues": "{{Range: 2, 10}}",
    "Default": "2",
    "Type": "integer",
}
```

Will make the option as slider with a range of 2 - 10. Without the allow values, it will function as a text box that only accept integer value.

setting the type to label will behave like label in GMCM:
```
"A label": {
    "Type": "Label"
}
```

**Comment by Pathoschild** [comment]
Thanks for the suggestions!

Content Patcher gets the option type automatically; that's how it shows checkboxes without `type: boolean` for example. I'll add a slider for numeric range options in the next update:
> ![example slider](https://user-images.githubusercontent.com/230581/105637624-6629db80-5e3c-11eb-8c44-0da045d71011.png)


As for label, the GMCM integration lets players edit the `ConfigSchema` field, which only contains config-related fields. Layout concerns like section labels are out of scope for that section unfortunately.

**Comment by Pathoschild** [comment]
Added in the upcoming Content Patcher 1.19.5.
