### ISSUE TITLE
[Automate][Lookup Anything] Not working with Prismatic Tools

### ISSUE THREAD

**Issue by L30Bola** [Pathoschild/LookupAnything#605]
Hi!
So, I have Prismatic Tools and Automate installed and just discovered that Automate doesn't automatically put Prismatic Shards into the Furnace. Made a quick video on this:

https://user-images.githubusercontent.com/10711497/105806071-0b020100-5f82-11eb-9f1a-e0c567777f18.mp4

Also, on Lookup Anything on inspecting the Furnace the Prismatic Bars "recipe" doesn't show there:

https://user-images.githubusercontent.com/10711497/105806358-9a0f1900-5f82-11eb-901e-53537bfd099c.mp4

**Comment by Pathoschild** [comment]
Hi! Due to how machines work in the game, Automate can't recognize custom recipes added to the vanilla machines by default. Prismatic Tools need to would [register its custom recipes with Automate](https://github.com/Pathoschild/StardewMods/blob/develop/Automate/technical.md) in its code.
