### ISSUE TITLE
[Content Patcher] Allows in depth patching for JsonAsset

### ISSUE THREAD

**Issue by Warilized** [Pathoschild/LookupAnything#610]
If it's feasible. Add support for editData to be used on JsonAssets mod.
To allow editing field such as Price or Crafting recipe. For configuration purpose and other such as changing the base price on certain season/year.

**Comment by Pathoschild** [comment]
Hi! That should already be possible using the [Json Assets-provided tokens](https://github.com/spacechase0/JsonAssets#content-patcher-api). Feel free to ask in [#making-mods on Discord](https://smapi.io/community#Discord) if you have any questions.

**Comment by Warilized** [comment]
Oh I don't know CP can do that, I thought it can only patch sprites.
Thanks, will ask later if i have the time
