### ISSUE TITLE
[Content Patcher] Suggestion: Adds Label for GMCM

### ISSUE THREAD

**Issue by Warilized** [Pathoschild/LookupAnything#614]
Assigning label type to `ConfigSchema` are out of scope as you've said in my post #602.
So how about creating a new field called `ConfigParent` or something along the lines?
Is it feasible?

I'm thinking the structure would be like this
```
"ConfigParent": {
       "A Label": {
              "Name": "A label of some short", //This is used as the display, while 'A Label' is used as reference.
              "Order": "1", //optional for ordering.
              "Description": "A label for grouping"
              }
       },
"ConfigSchema": {
       "Config A": {
              "AllowValues": "1, 2",
              "Default": "1",
              "Description": "Config children or something",
              "Parent": "A Label"
              },
...
       }
```
Not assigning a `parent` in `ConfigSchema` will make the config be placed on the topmost part
And the setting in the GMCM will be something like this.

> Config B
**A label of some sort**
Config A

It doesn't add `config.json` with unnecessary stuff and will remain as usual. But will be grouped in the GMCM interface.

It probably will be pretty hard to implement.

**Comment by Pathoschild** [comment]
Hi! Unfortunately setting UI labels or hierarchy is out of scope. Content Patcher automatically generates a UI to match the config schema, the content pack doesn't control how the options are shown in UIs. For example, in the future it could be editable through a different mod, which may not support grouping labels or may use a different paradigm.

**Comment by Warilized** [comment]
oh, thanks for answering!
Sorry if i suggest too much idea haha :D
