### ISSUE TITLE
[Content Patcher] Custom Locations and Warps

### ISSUE THREAD

**Issue by wamc2017** [Pathoschild/LookupAnything#618]
Hi,

I tried to add a custom location with ContentPatcher v1.21 and I'm having a little issue to get the warps working.
My content.json can be found here: https://smapi.io/json/content-patcher/1e943409d6e24af7bb55f52d9a3a28e2

The warp from the town to the new area works without problems, but the warp back to the town doesn't work.
I checked patch summary and it seems the EditMap for the custom area doesn't get applied.
Here's the log just in case: https://smapi.io/log/80682afc59bc439e94ec1e727cdf9a5f

Thanks for looking into it. 
wamc

**Comment by Pathoschild** [comment]
Hi! The Content Patcher 1.21 alpha is only available on the Stardew Valley Discord, so I assume you're on that server? If so, ping/message me with a zip of your content pack there and I'll help. I'll close this ticket though, since I only use GitHub issues to track development tasks.
