### ISSUE TITLE
[Fast Animations] Speed Up Leveled Water Can Animations

### ISSUE THREAD

**Issue by T-Miner** [Pathoschild/LookupAnything#62]
I would love to see the multiple stages of the watering can animation be sped up. The watering can should just use the widest area quickly as possible.

**Comment by Denifia** [comment]
I like the idea but always using the widest area possible would use a large amount of water each time. If you only need to water one square, it shouldn't use water for 9 squares.

Maybe just start with speeding up the animation and seeing if that is enough?

**Comment by ghost** [comment]
@mralbobo's [tool charging mod](https://github.com/mralbobo/stardew-tool-charging) does this with both the watering can and hoe, though it'd be nice to see this implemented in Fast Animations.

**Comment by Pathoschild** [comment]
I think skipping charge levels is best handled by the [Tool Charging mod](https://github.com/mralbobo/stardew-tool-charging) (which is linked from the Fast Animations mod page now). Fast Animations only speeds up animations, it deliberately doesn't change any game mechanics like that.
