### ISSUE TITLE
Can't get golden walnuts in island farm when harvesting with Tractor

### ISSUE THREAD

**Issue by scriptsforweirdos** [Pathoschild/LookupAnything#622]
The 5 golden walnuts from harvesting crops in the island farm only appear if you harvest one-time crops by hand. Harvesting one-time crops by tractor doesn't trigger a walnut event.

NB: I know that walnuts don't appear when harvesting regrow crops but that's a game thing and not a tractor thing.

SMAPI 3.9.1
Stardew 1.5.4 Windows
Tractor 4.13.3

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Tractor Mod 4.14. Thanks for reporting it!
