### ISSUE TITLE
[Automate] Automation doesn't work inside shed in multiplayer

### ISSUE THREAD

**Issue by bjsswanson** [Pathoschild/LookupAnything#626]
Mod is installed on both host and guest. No machines are pulling from or to the chests inside a shed.

Running "automate summary" on the SMAPI console does not show the machine groups in the shed, but using the overlay on both host and guest in the shed shows the machine groups marked in green.

**Comment by bjsswanson** [comment]
Below is the version information and other installed mods (may be causing a conflict?):

[SMAPI] SMAPI 3.9.1 with Stardew Valley 1.5.4 on Microsoft Windows 10 Home
[SMAPI] Mods go here: E:\SteamLibrary\steamapps\common\Stardew Valley\Mods
[SMAPI] Starting game...
[SMAPI] Loaded 9 mods:
[SMAPI]    Automate 1.21.0 by Pathoschild | Lets you automate crafting machines, fruit trees, and more by connecting them to chests.
[SMAPI]    Chests Anywhere 1.20.9 by Pathoschild | Access your chests from anywhere and organize them your way.
[SMAPI]    Console Commands 3.9.1 by SMAPI | Adds SMAPI console commands that let you manipulate the game.
[SMAPI]    Error Handler 3.9.1 by SMAPI | Handles some common vanilla errors to log more useful info or avoid breaking the game.
[SMAPI]    Lookup Anything 1.32.4 by Pathoschild | View metadata about anything by pressing a button.
[SMAPI]    MultiPause 1.1.2 by Taw | Adds mechanisms for time to be paused in multi-player when players are in menus or other situations that would normally pause time in single-player mode.
[SMAPI]    Save Backup 3.9.1 by SMAPI | Automatically backs up all your saves once per day into its folder.
[SMAPI]    SkipFishingMinigame 0.2.0 by DewMods | When a fish bites, just hook the fish and skip the minigame
[SMAPI]    Tractor Mod 4.13.3 by Pathoschild | Lets you buy a tractor to more efficiently work with crops, clear twigs and rocks, etc.

**Comment by bjsswanson** [comment]
Nevermind, I guess the location was not dynamically added to the list of locations to automate when it was constructed during the session. Restarting the game sorted the issue.

**Comment by Pathoschild** [comment]
Hi! That's a known issue with SMAPI events; see Pathoschild/SMAPI#710 for more info.
