### ISSUE TITLE
[Tractor Mod] Safety Keybind & config.json Options

### ISSUE THREAD

**Issue by firereverie** [Pathoschild/LookupAnything#632]
Add keybind for safety keybind & additional tool selection with following functions;

  Standard Operation

    Replace holdToActivate with stndOp keybind

    Adds modes

      holdNO
        functionally equivalent to holdToActivate, activates tool functions/custom implements defined under config stndOp tools 

      holdNC, default 
        Opposite of holdToActivate, disables all tool functions while held

      toggle
        Defaults to On state incase no keybind

  Safety Operation

    Adds safety keybind & config.json options

    Same tool definition options in config.json as stndOp

    Mode options

      holdNO, default
        Any tool function enabled under safety options will only engage while holding key

      holdNC
        Any tool function/custom implement listed under safety heading disabled while holding key

      toggle
        Defaults to off state

**Comment by Pathoschild** [comment]
Thanks for the suggestions! I prefer minimizing configuration options to keep the mod relatively simple and testable though (especially for a mod like Tractor Mod which inherently has a lot of configuration already). So unless it's an option many players would use, I'd rather keep it simple in this case. Sorry!
