### ISSUE TITLE
[Tractor Mod] Soul of a Junimo

### ISSUE THREAD

**Issue by firereverie** [Pathoschild/LookupAnything#635]
Automation for farming functions.

  Keybind

  Modes
    holdNO
    holdNC
    toggle, default
  
  Tool Config

**Comment by Pathoschild** [comment]
Hi! I'm not sure what this suggestion is about, but I'll close this ticket since I don't track suggestions through GitHub issues. Feel free to add a comment on the [Nexus mod page](https://www.nexusmods.com/stardewvalley/mods/1401) with more details though!
