### ISSUE TITLE
[Content Patcher] Possible memory leak on Ubuntu

### ISSUE THREAD

**Issue by raqu73** [Pathoschild/LookupAnything#640]
When using Content Patcher mods, the game's memory usage gets out of control on Ubuntu 20.04. The most noticeable was Elle's Seasonal Buildings, memory usage increased by ~100MB each time I entered the farm map. It seems to happen with most if not all Content Patcher mods, though much slower.

**Comment by Pathoschild** [comment]
Does that still happen if you edit the `smapi-internal/config.json` file in your game folder and enable the `AggressiveMemoryOptimizations` option? (Note that's an experimental feature and may cause crashes.)

**Comment by raqu73** [comment]
Enabled it and seems to be no different - if it's helping, it's not by much. Got it up to ~6.1 GB of usage then stayed on the map for a bit, usage never started to decrease. It definitely feels like it's just Seasonal Buildings doing this now that I've had a bit longer to test, it was playable for hours with that one specifically disabled, odd.

**Comment by Pathoschild** [comment]
As a test I installed [Seasonal Buildings](https://www.nexusmods.com/stardewvalley/mods/1993) on Windows, and continuously warped between the farmhouse and farm; I didn't see any noticeable increase in memory usage. Does that still happen if you temporarily remove all mods except Content Patcher, Seasonal Buildings, and SMAPI itself?

**Comment by raqu73** [comment]
Indeed, occurs with just those included. Tried with AggressiveMemoryOptimizations enabled and disabled as well.

**Comment by Pathoschild** [comment]
If you keep doing it until the game runs out of available memory, does memory usage stabilize at that point or does the game crash with an `OutOfMemoryException` error?

**Comment by Pathoschild** [comment]
I'll close this due to missing info, but there's a number of performance improvements in recent versions that might help with that.
