### ISSUE TITLE
[Tractor Mod] Engage action only when left mouse button is pressed.

### ISSUE THREAD

**Issue by mekkanik** [Pathoschild/LookupAnything#643]
Have the tractor do stuff with ax, pickax, planting, harvesting when left mouse button is pressed. Will avoid a lot of accidental planting and fertilizing. Can also make this a toggleable key stroke that engages or disengages the tractor.

**Comment by Pathoschild** [comment]
Hi! That's already supported; see the `HoldToActivate` option in the [mod configuration](https://github.com/Pathoschild/StardewMods/tree/develop/TractorMod#configure).

**Comment by mekkanik** [comment]
oooooo thanks. I missed that one!!
