### ISSUE TITLE
[Automate] Allow mini shipping bins to restrict to artisan goods

### ISSUE THREAD

**Issue by mekkanik** [Pathoschild/LookupAnything#645]
I think mini shipping bins have potential to be the automatic selling point for stacks of aged stuff from the cellar. That is if you can live with the idea of Lewis skulking inside your cellar. Anyways, couple of options there. "Pick up artisan goods only." This will restrict auto sell to only group -27. "Restrict to iridium quality only." Best used in the cellar where aged stuff is automatically sold.

P.S. I'm available to help with this :)

**Comment by Pathoschild** [comment]
Hi! I think the ideal would be a generic filter UI we can reuse in a few places (e.g. for chest input/output and shipping bin input). I'm mainly focusing on SMAPI + Content Patcher + maintaining abandoned mods for now, so it'll be a while before I can look into it. Pull requests are welcome if you want to work on it though!

**Comment by Pathoschild** [comment]
I'll close this ticket since I don't have any plans to work on it currently, but feel free to ping me on the [Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord) if you want to discuss further!
