### ISSUE TITLE
[Content Patcher] Allow dependent mods to access the dependency's config values

### ISSUE THREAD

**Issue by lshtech** [Pathoschild/LookupAnything#647]
As an example: the Gender Neutrality Mod has a variety of config values that it plugs into it's modded dialogue, if you wanted to create a mod that supports that sort of dialogue modification you might need to be able to know what pronouns, etc. were chosen.

Perhaps automatically setting them as mod provided tokens so they could be accessed by {{ModId/ConfigName}}.

**Comment by Pathoschild** [comment]
@Ishtech Thanks for the suggestion! I'll close this since I don't track suggestions as GitHub issues, but I have something like that on my list of ideas for future versions.
