### ISSUE TITLE
[Automate] Suggestion for config to only allow stone chests

### ISSUE THREAD

**Issue by DarkYuan** [Pathoschild/LookupAnything#649]
Automate's great, but often it does more than I intend it to do, if I'm working with chests near machines. It'd be nice to confine it to only pull/push from a stone chest for example, and to ignore wooden chests. Or even the other way around.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! I'll close this since I don't track suggestions/ideas on GitHub, but that's on my list of ideas for future versions.
