### ISSUE TITLE
Artisanvalley help

### ISSUE THREAD

**Issue by PrincessPrudence** [Pathoschild/LookupAnything#651]
I need help with your mod for android I have your mods for pc but there is a slight problem using the mod on mobile when I downloaded the artisan valley mod is says it needs 
( ppja. Artisanvalley machines pmf is depnds on ppja. artisanvalley machines ja please install this first) when I look back in my mods folder it's already in there. So I am not sure what's going on but it's kinda pissing me off and I really like your mods but idk please help me.
![Screenshot_20210805-102033_My Files](https://user-images.githubusercontent.com/40625573/128371546-178cbf29-f893-4a3e-be37-d7e966dfa6f2.jpg)
![Screenshot_20210805-101634_SMAPI Installer](https://user-images.githubusercontent.com/40625573/128371549-ff559d7d-70e3-435c-a76b-f838c142949a.jpg)
![Screenshot_20210805-101419_SMAPI Installer](https://user-images.githubusercontent.com/40625573/128371552-146a05b5-a88d-457b-be32-2bd91133f7ca.jpg)
![Screenshot_20210805-101413_SMAPI Installer](https://user-images.githubusercontent.com/40625573/128371553-208ab0cd-f367-4c28-9e50-6264cdfbb2ba.jpg)
![Screenshot_20210805-101152_SMAPI Installer](https://user-images.githubusercontent.com/40625573/128371555-cb9d7aa1-7d16-4258-834b-00364fa3e5ff.jpg)
![Screenshot_20210805-100437](https://user-images.githubusercontent.com/40625573/128371558-b263db29-f669-4f20-bea8-50538d553b60.jpg)

**Comment by PrincessPrudence** [comment]
Okay nvm on the first problem I need to figure out this 
![Screenshot_20210805-112603](https://user-images.githubusercontent.com/40625573/128377114-20e041ed-42b3-4248-8e2c-e097809a8542.jpg)

**Comment by Pathoschild** [comment]
Hi! None of those mods are part of this GitHub repo. If you [come ask in #using-mods on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord), we'll help you get it all working though.

**Comment by PrincessPrudence** [comment]
I did and it got me nowhere so I am scrapping all of it now and staring
over because it's making me mad
