### ISSUE TITLE
Have compiled releases also available as GitHub Releases

### ISSUE THREAD

**Issue by SQLCanuck** [Pathoschild/LookupAnything#658]
In order to give people more options on where to download your amazing mods, perhaps the zip files of the compiled releases could also be made available as GitHub Releases.

**Comment by Pathoschild** [comment]
Hi! All of my [Nexus](https://www.nexusmods.com/stardewvalley) mods are automatically synced to [ModDrop](https://www.moddrop.com/stardew-valley/), which doesn't require an account to download.
