### ISSUE TITLE
LooseSprites/Giftbox

### ISSUE THREAD

**Issue by MaythornRose** [Pathoschild/LookupAnything#659]
I've been having an issue where I can't get a mod for LooseSprites/Giftbox to load until I actually click on the giftbox.

 Patch summary says this:

```
Toned Down Giftbox:
-------------------

   Patches:
      loaded  | conditions | applied | name + details
      ------- | ---------- | ------- | --------------
      [X]     | [X]        | [ ]     | Load LooseSprites/Giftbox
```

Can you double check to see if CP is loading in changes for that file?
Sorry, it's so minor a thing, but the color has been bugging me for YEARS.
[[CP] Toned Down Giftbox.zip](https://github.com/Pathoschild/StardewMods/files/7157691/CP.Toned.Down.Giftbox.zip)

**Comment by Pathoschild** [comment]
Fixed in the upcoming SMAPI 3.12.7 and 3.13.0-beta. Thanks for reporting it!

![screenshot](https://user-images.githubusercontent.com/230581/133166336-c4e75841-9cec-4d17-ac84-1ee29844f8aa.png)
