### ISSUE TITLE
Customize Exterior crash when opening customize menu.

### ISSUE THREAD

**Issue by Hamikins** [Pathoschild/LookupAnything#660]
Hi Pathoschild. Thanks for maintaining this mod for us.

I'm posting this here as well as NexusMods just in case you don't see it.

When I installed this mod I get an error when I try and double right click a building and it crashes the game. I do have a lot of mods installed and that's probably a reason why.

I googled the error and found that someone getting the same error with a different mod said that changing their resolution to the correct (larger) one for their monitor fixed their issue. No luck for me.

I updated all the mods that needed it. Some I didn't because they wanted me to use a beta version etc.

Error Log: https://smapi.io/log/7db49c198faa48f5a758e80422f533e9

**Comment by Pathoschild** [comment]
Hi! Customize Exterior isn't one of my mods; did you mean to report this on [spacechase0/StardewValleyMods](https://github.com/spacechase0/StardewValleyMods)?
