### ISSUE TITLE
[Tractor Mod] Seed bag does not trigger Enricher enhancement to sprinklers

### ISSUE THREAD

**Issue by scriptsforweirdos** [Pathoschild/LookupAnything#675]
The Enrichers which you purchase from Qi's shop are supposed to distribute fertilizer when you plant seeds. However, when planting using the seed bag on the Tractor the Enrichers don't fire.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Tractor Mod 4.14.10. Thanks for reporting it!
