### ISSUE TITLE
[Automate] Connecters do not work

### ISSUE THREAD

**Issue by mezen** [Pathoschild/LookupAnything#716]
Hi,

I tried to use a connector to connect the mushroom cave objects, but the Wood Floor do not work as connecter but is activated in the options menu.

![automate1](https://user-images.githubusercontent.com/1306409/153624526-068773f0-740c-4b55-b7ae-83802e36ec0c.png)

![automate2](https://user-images.githubusercontent.com/1306409/153624538-c9daec98-908f-4933-b764-53f679e97f40.png)

![automate3](https://user-images.githubusercontent.com/1306409/153624545-de8a5d22-28d3-4fe2-9c19-90ee298d7728.png)

**Comment by Pathoschild** [comment]
Hi! You enabled the Wood Floor (_Holzboden_) option, but you placed a Wood Path (_Holzpfad_). It should work if you enable that one in the options too.

**Comment by mezen** [comment]
Yes, that was my stupid error. Sorry^^
