### ISSUE TITLE
[Chests Anywhere] Bug: both cursors used when using controller

### ISSUE THREAD

**Issue by TheRaven81** [Pathoschild/LookupAnything#72]
When using a controller to play, after pressing B on the Keyboard the game uses both cursors(the hand and the arrow), with the arrow cursor on top of the hand.
![2017-06-19- 001](https://user-images.githubusercontent.com/676345/27303079-8bce89fe-5507-11e7-9ec3-108e1229b7d2.png)
It also happens when walking up to a chest and opening it normally.
![2017-06-19- 002](https://user-images.githubusercontent.com/676345/27303974-861862fc-550a-11e7-99e1-c42e0f3ce1ce.png)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the next release.
