### ISSUE TITLE
PPJA MIZU'S FLOWERS

### ISSUE THREAD

**Issue by KAVH5** [Pathoschild/LookupAnything#733]
Hi, firstly, I am sorry if this is not the appropriate place or if you are the not the correct person to be reaching out to. I have the Mizu's Flower mod which I know was created by paradigmnomad. As far as I know they no longer make/update mods an I thought any still active were suppose to be referred to Pathoschild but I am not sure how to message you. 

Any who, hopefully a small issue? SVE had an update an once updated there is an error in the log, red in color and says,  

[Json Assets] Duplicate object: Rafflesia just added by Mizu's Flowers for JsonAssets, already added by New Objects for Stardew Valley Expanded!

Will this hurt my game or is it okay to ignore?

SMAPI LOG: https://smapi.io/log/999d1095d60b445ba7724e50186d4bbd

Thank you for your time.

**Comment by ellipszist** [comment]
You can update Stardew Valley Expanded 1.14.13 to fix this issue.

https://www.nexusmods.com/stardewvalley/mods/3753

**Comment by KAVH5** [comment]
Thank you!! I actually just did and was coming back to say it was fixed! I loaded it before work so it would be ready when I got home, I hadn't realize there was another update ;P

**Comment by Pathoschild** [comment]
Glad you got it working! Feel free to message me through Nexus Mods for any others questions about ParadigmNomad's mods there.
