### ISSUE TITLE
[Lookup Anything] Spanish translation

### ISSUE THREAD

**Issue by ThomasGabrielDelavault** [Pathoschild/LookupAnything#74]
Hello, this is my spanish translation.

[es.zip](https://github.com/Pathoschild/StardewMods/files/1120938/es.zip)

**Comment by Pathoschild** [comment]
Thanks @ThomasGabrielDelavault! There's a few new messages in the next version; can you translate these too?
```javascript
    // NPC child lookup labels
    "npc.child.age": "Age",

    // NPC child lookup values
    "npc.child.age.description-partial": "{{label}} ({{count}} days to {{nextLabel}})",
    "npc.child.age.description-grown": "{{label}}",
    "npc.child.age.newborn": "newborn",
    "npc.child.age.baby": "baby",
    "npc.child.age.crawler": "crawler",
    "npc.child.age.toddler": "toddler",
```

**Comment by ThomasGabrielDelavault** [comment]
Ok.

**Comment by ThomasGabrielDelavault** [comment]
[es.zip](https://github.com/Pathoschild/StardewMods/files/1122663/es.zip)

That's the final one.

**Comment by Pathoschild** [comment]
@ThomasGabrielDelavault Thanks again! I added the translations to the next release. Are you interested in translating any new messages added in future versions of Lookup Anything?

**Comment by ThomasGabrielDelavault** [comment]
Yes!, no problem.

**Comment by Pathoschild** [comment]
@ThomasGabrielDelavault One more translation for the next release. This is a message shown under 'complaints' when you look up a farm animal:
```json
"animal.complaints.wild-animal-attack": "attacked by wild animals during the night"
```

**Comment by ThomasGabrielDelavault** [comment]
"atacado/a por animales salvajes durante la noche".
Sorry, im in the phone.

**Comment by Pathoschild** [comment]
Thanks!
