### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tragco** [Pathoschild/LookupAnything#756]
Hi! What code do I use to make a texture unique only to Ginger Island, please if you know?

**Comment by Pathoschild** [comment]
Hi! If you mean in a content pack for Content Patcher, you can use the [`LocationContext` token](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-guide/tokens.md#LocationContext). For example:
```js
{
    "Action": "EditImage",
    "Target": "Characters/Abigail",
    "FromFile": "assets/abigail-island.png",
    "When": {
        "LocationContext": "Island"
    }
}
```

If you have any other questions, come ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll be happy to help! The GitHub issues here are only used to track specific development tasks, so most modders who could help won't see questions here.
