### ISSUE TITLE
Update Spanish translations for Noclip Mode

### ISSUE THREAD

**Issue by bpblog** [Pathoschild/LookupAnything#757]
`
    /*********
    ** In-game messages
    *********/
    "enabled-message": "Noclip ha sido habilitado; apretar {{button}} otra vez para inhabilitarlo.",
    "disabled-message": "Noclip ha sido inhabilitado; apretar {{button}} otra vez para habilitarlo.",

    /*********
    ** Generic Mod Config Menu UI
    *********/
    // TODO
    "config.title.general-options": "Opciones Generales",
    "config.enabled-message.name": "Mostrar mensaje habilitado",
    "config.enabled-message.desc": "Muestra un mensaje en el juego, en la esquina de la pantalla cuando el modo No Clip está activado.",
    "config.disabled-message.name": "Mostrar mensaje deshabilitado",
    "config.disabled-message.desc": "Muestra un mensaje en el juego, en la esquina de la pantalla cuando el modo No Clip está desactivado.",

    "config.title.controls": "Controles",
    "config.toggle-key.name": "Alternar Tecla",
    "config.toggle-key.desc": "Las teclas que activan o desactivan el modo No Clip en el juego."`

**Comment by Pathoschild** [comment]
Added to the upcoming Noclip Mode 1.3.4. Thanks for the help!
