### ISSUE TITLE
Stamina on Tractor

### ISSUE THREAD

**Issue by Shirkit** [Pathoschild/LookupAnything#761]
Hello,

Would it be possible to add some kind of config for stamina drain while using the tractor? Maybe distance based or tool based drain, configurable. Would be like it's a "lot of work" to run a tractor and to work with it, as it requires a lot of attention.

Anyways, it's just an ideia I'd be thrilled to incorporate on my gameplay.

Thank you!

**Comment by Pathoschild** [comment]
Hi! Balance options are on my list of ideas for future versions (which may include stamina, water, or fuel drain). I'll close this since I only use GitHub issues for specific development tasks, but thanks for the suggestion!
