### ISSUE TITLE
[Json Assets and Content Patcher] Giant Crops

### ISSUE THREAD

**Issue by StrangePanda0** [Pathoschild/LookupAnything#765]
I've been wondering how can i get the ID of giant crops? so i can make animated texture of my mod.

**Comment by Pathoschild** [comment]
Hi! I don't think Json Assets adds tokens for giant crops currently. I suggest asking on [that mod's repo](https://github.com/spacechase0/StardewValleyMods), or [on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) where the author is more active.
