### ISSUE TITLE
[Lookup Anything] Crash on Looking up Tiles

### ISSUE THREAD

**Issue by DemonBigj781** [Pathoschild/LookupAnything#770]
https://smapi.io/log/36abf7ed10c24cde866210951a5678aa?Mods=LookupAnything

all i did was press f7 on a BigCraftable I made on an upcoming mod. f7 is my lookup key.

all of the BigCraftables i made use the same size sprite sheet and only halve of the machines can be looked up.

**Comment by DemonBigj781** [comment]
here is a new log with debug info https://smapi.io/log/cf3d5801a7e546918cdaf9e358ea085f

**Comment by Pathoschild** [comment]
Hi! Can you come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? Feel free to ping me there with `@Pathoschild#0001` if you don't get an answer.

**Comment by Pathoschild** [comment]
I'll close this ticket since I don't use GitHub issues for user support, but feel free to comment on [the Lookup Anything mod page](https://www.nexusmods.com/stardewvalley/mods/541) if you still need help.
