### ISSUE TITLE
[Automate] Junimo Chest Networks

### ISSUE THREAD

**Issue by CyprusGrunumn** [Pathoschild/LookupAnything#773]
While working on automating my entire farm, I noticed that the junimo chests are shared, no matter how many they are all the same 3x3 inventory.
It would be really neat if we could use the color picker on the junimo chests, and each color chest only connected to other junimo chests of the same color. This would allow for different 'Networks' of chests, each serving their own purpose.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! I'll close this ticket since it's out of scope for my current mods, but something like that is on my list of ideas for future projects.
