### ISSUE TITLE
Needing help making a mod compatible with stardew valley expanded 🥺

### ISSUE THREAD

**Issue by SSakuraUsagi** [Pathoschild/LookupAnything#788]
There is a mod I would love more than anything to play, but I absolutely always have to have SVE installed... it is a must have... I'm wondering if anyone could help me out by making a few changes to the SDS mod so it's compatible with SVE. 

Link here: https://www.nexusmods.com/stardewvalley/mods/8324 

Thank you! <33

**Comment by Pathoschild** [comment]
Hi! That's not one of my mods, so I can't really help with it. You could try asking on that mod's page though, or in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord) to discuss with more mod authors.
