### ISSUE TITLE
[Automate] Hoppers are being automated, breaking the Super Hoppers mod

### ISSUE THREAD

**Issue by VariableVixen** [Pathoschild/LookupAnything#792]
It looks like hoppers, including [super hoppers](https://www.nexusmods.com/stardewvalley/mods/9418)﻿, are technically chests, so Automate isn't ignoring them properly. Using [Lookup Anything](https://www.nexusmods.com/stardewvalley/mods/541)﻿, I've confirmed that super hoppers are given a mod data field named `spacechase0.SuperHopper` (with a constant value of `"1"` according to [their source](https://github.com/spacechase0/StardewValleyMods/blob/fd60a69528e6f51fa57d63bb9fe8912a6fff5d0a/SuperHopper/Mod.cs#L58)), so maybe Automate can be updated to ignore any "chest" objects that have that field?

Alternatively, maybe Automate should just ignore all hoppers? It looks like Super Hoppers has [a check to only operate on hopper tiles](https://github.com/spacechase0/StardewValleyMods/blob/fd60a69528e6f51fa57d63bb9fe8912a6fff5d0a/SuperHopper/Mod.cs#L129)﻿ that could probably be used by Automate to filter them out.

My log is [available](https://smapi.io/log/0669461bdec64469a921dca294356ee3)﻿ as requested.

**Comment by VariableVixen** [comment]
I've never modded Stardew, and I'm only looking through the online source code here, but I _think_ that [`MachineGroupFactory.GetEntity()`](https://github.com/Pathoschild/StardewMods/blob/5fa631590136b3515b084434ecc9c30e4b101e8c/Automate/Framework/MachineGroupFactory.cs#L198) might be the place to add this check. Specifically, I think it would go in the [`case SObject obj` block](https://github.com/Pathoschild/StardewMods/blob/5fa631590136b3515b084434ecc9c30e4b101e8c/Automate/Framework/MachineGroupFactory.cs#L205-L218), checking if `obj is Chest { SpecialChestType: Chest.SpecialChestTypes.AutoLoader }` and returning `null` in that case. It could probably go just above the call to `this.GetEntityFor()`, if I'm understanding the code correctly.

My reasoning for ignoring _all_ hoppers is that Automate basically obsoletes normal hoppers by allowing chests to perform the same function. Rather than placing a hopper, which must be specifically _above_ a given machine, a chest can be placed anywhere in a valid machine group with it, and perform identically as well as optionally accepting output from the machine at the same time.

**Comment by Pathoschild** [comment]
Hi! They're already ignored in the lower-level `AutomationFactory.GetFor`, which skips any hoppers with `spacechase0.SuperHopper` in their mod data. Automate isn't notified when a regular hopper becomes a super hopper though, so you may need to pick up a machine and put it back down to trigger an update.
> ![image of ignored super hopper](https://user-images.githubusercontent.com/230581/222918735-416c9aef-8553-473c-a15a-6730fb65e9f9.png)

Otherwise Automate treats regular hoppers as output-only chests, which gives them a use that's slightly distinct from default chests.

**Comment by VariableVixen** [comment]
Ah! That would certainly be why my setup wasn't working. I had the groups I wanted in place, then I added a hopper and applied the iridium bar to convert it. It sounds like I need to, after doing that, place and/or remove another automatable tile of any type within the new overall group (the one including the hoppers) in order for Automate to rescan everything? I'm assuming a chest should suffice and that the _entire_ overall joint group will be broken up, even if it consists of three or more "actual" groups separated by hoppers.

For context, I'm using the [Packing Boxes and Crates mod](https://www.nexusmods.com/stardewvalley/mods/8751) and what I'm trying to do is process ingredients in group A, hopper them into group B where that mod's crating machines will operate on them, then hopper the crated goods into "group" C which consists of the shipping bin.

**Comment by Pathoschild** [comment]
Yep. Automate will also rebuild machine groups when you reload the save, so any previous super hoppers will be ignored correctly. You can press `U` in-game to show the automation overlay, so you check whether a super hopper is being ignored and your machine groups are split as you expect.
