### ISSUE TITLE
How to use DebugMode

### ISSUE THREAD

**Issue by c469591** [Pathoschild/LookupAnything#797]
Hello, I'm a new player to the game.
I have put the mod in the specified directory according to the instructions.
SMAPI has also been installed.
But I opened the game, using the shortcut keys introduced in the instructions did not have any effect.
I'm sorry, I'm still a rookie.
Thank you!

**Comment by Pathoschild** [comment]
Hi! Can you post a comment on the [the Debug Mode mod page](https://www.nexusmods.com/stardewvalley/mods/679) with the above info, and add a [link to your SMAPI log](https://smapi.io/log)? I'll help you there, since I don't use GitHub issues for mod support.
