### ISSUE TITLE
[Content Patcher] Parameter 'name' cannot be null Error.

### ISSUE THREAD

**Issue by DeLiXx** [Pathoschild/LookupAnything#820]
[Cape Stardew](https://www.nexusmods.com/stardewvalley/mods/14635) is using Content Patcher to edit [Unlockable Bundles ](https://www.nexusmods.com/stardewvalley/mods/17265)`UnlockableBundles/Bundles` asset.
Initial asset load: [link](https://gitlab.com/delixx/stardew-valley/unlockable-bundles/-/blob/main/Unlockable%20Bundles/Lib/AssetRequested.cs)
Asset model: [link](https://gitlab.com/delixx/stardew-valley/unlockable-bundles/-/blob/main/Unlockable%20Bundles/Lib/UnlockableModel.cs)

In previous versions of Cape some users reported the following error:
```
Patch error: CapeStardew > Include Data/CapeUnlockableBundles.json > EditData UnlockableBundles/Bundles #2 failed on context update (see log file for details).
Value cannot be null. (Parameter 'name')
```
[Smapi Log](https://smapi.io/log/655b655fd836408fbe74117df7bbfe3d)

But the error did not happen for either of us.
I was able to reproduce it by chance when testing their mod.
Commenting out "When" conditions caused this error, which led me to believe that having two seperate changes with the same action, target and when conditions in the same file caused it.
The latest version of Cape however now always throws this error when starting a new game, but not when loading a existing game.

[User SMAPI log](https://smapi.io/log/f45ce228adda4690862173f6ef5f6b0d)
[Reproduced SMAPI log](https://smapi.io/log/c8aa29f1ad034fc9a211621854abcc8b?Levels=trace%7Edebug%7Einfo%7Ewarn%7Eerror%7Ealert%7Ecritical&Page=2&PerPage=1000&Mods=game%7ESMAPI%7EContentPatcher)

To reproduce:
1. Install Cape Stardew
2. Create a new single player game

Attached is a minimum viable product version of Cape, which only requires Unlockable Bundles and JsonAssets to run.
[Cape Stardew MVP.zip](https://github.com/Pathoschild/StardewMods/files/12513824/Cape.Stardew.MVP.zip)

**Comment by DeLiXx** [comment]
Hello, I recognise you're quite busy with 1.6 at the moment, but could you perhaps provide a ETA for when you're able to address this issue?

**Comment by DeLiXx** [comment]
Issue can be closed

**Comment by Pathoschild** [comment]
This specific case was fixed in Unlockable Bundles, but the upcoming Content Patcher 1.29.5 no longer tries to apply non-ready tokens to the JSON structure. The patch will now correctly be marked non-ready instead. Thanks for reporting it!
