### ISSUE TITLE
[Automate] Looms don't accept yellow couches

### ISSUE THREAD

**Issue by Accardi22** [Pathoschild/LookupAnything#846]
![image](https://github.com/Pathoschild/StardewMods/assets/88256507/67cef357-cae7-40a6-8e1c-59ac539bc823)
![image](https://github.com/Pathoschild/StardewMods/assets/88256507/700f8a83-6581-48ff-ab59-8591f9744dbf)
![image](https://github.com/Pathoschild/StardewMods/assets/88256507/fe93e687-4a1d-4731-adf2-0d3e4c44672d)
![image](https://github.com/Pathoschild/StardewMods/assets/88256507/1da06a78-5cf5-4d22-8b9f-fd768792d708)

**Comment by Pathoschild** [comment]
Automate implements the machine recipes directly, so it's not affected by glitches like that. The yellow couch glitch is also fixed in the upcoming Stardew Valley 1.6, and the next Automate update will be for 1.6 anyway. Thanks for reporting it though!
