### ISSUE TITLE
[Automate]Mushroom Log Error

### ISSUE THREAD

**Issue by iamsaulc** [Pathoschild/LookupAnything#857]
An error occurred when a Mushroom Log generated a mushroom when extracting it, the item disappeared and generated the following error:
[https://smapi.io/log/edbd434c5f2545a087f873bc08546240?Mods=Automate](https://smapi.io/log/edbd434c5f2545a087f873bc08546240?Mods=Automate)

**Comment by Pathoschild** [comment]
This was fixed in Automate 2.0.3. Thanks for reporting it!
