### ISSUE TITLE
[Chests Anywhere] Upgrading a chest to a Big chest erases chest configuration

### ISSUE THREAD

**Issue by villainous-j** [Pathoschild/LookupAnything#859]
**Describe the bug**
Upgrading a chest to the big chest resets the chest's "Chests Anywhere" configuration to the default, losing the name, colour, category, etc. Fix would be to carry these configurations over to the Big chest automatically.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Place a chest.
2. Configure the chest to something that's not default, eg. Colour: Blue.
3. Upgrade the chest with a Big chest.
4. Notice the chest is no longer the colour set in step 2.

**Log file**
No errors displayed.

**Comment by Pathoschild** [comment]
Fixed in the upcoming Stardew Valley 1.6.9. Thanks for reporting it!

**Comment by villainous-j** [comment]
thank you so much!
