### ISSUE TITLE
[Automate] Destroyed Bushes Causes Errors

### ISSUE THREAD

**Issue by KankuroGB** [Pathoschild/LookupAnything#860]
**Describe the bug**
When you have a connection to a chest through a bush and that bush is destroyed it will create a reoccurring error until the chest is removed, replaced, etc.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save
2. Destroy a bush that has an Automate connection
4. Error occurs (continuously until you move the connected chest)

**Log file**
[Log File](https://smapi.io/log/4fbf02c5a3cb491bb6c2139fc4a58cb7)

**Comment by Pathoschild** [comment]
This was fixed in Automate 2.0.5. Thanks for reporting it!
