### ISSUE TITLE
[Content Patcher] The map does not change seasonally in custom languages.

### ISSUE THREAD

**Issue by ellipszist** [Pathoschild/LookupAnything#871]
**Describe the bug**
The map does not change seasonally in custom languages.

**To Reproduce**
Exact steps which reproduce the bug.
1. Install [Thai mod](https://www.nexusmods.com/stardewvalley/mods/7052).
2. Load save.
3. Open CJB Cheats Menu.
4. Click 'Time'.
5. Select 'Fall'.
6. Pass 'M' to open map.
7. The map does not change seasonally.

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/43781364/aa9c7944-4827-4198-96eb-e31b4578209e)

**Comment by ellipszist** [comment]
@Pathoschild

**Comment by Pathoschild** [comment]
This is fixed in the upcoming Stardew Valley 1.6.4. Thanks for reporting it!
