### ISSUE TITLE
[Content Patcher] {{DayEvent}} uses festival name from localized Data/Festivals/FestivalDates asset

### ISSUE THREAD

**Issue by ellipszist** [Pathoschild/LookupAnything#872]
**Describe the bug**
I found that if I translated the name of the festival in `\Data\Festivals\FestivalDates.json` will cause `DayEvent` to be translated as well, causing the `Seasonal Outfits - Slightly Cuter Aesthetic` mod to not be able to load festival outfits.

**To Reproduce**
Exact steps which reproduce the bug.
1. Install [Thai mod 2.4.2](https://www.nexusmods.com/stardewvalley/mods/7052?tab=files&file_id=85743) and [Seasonal Outfits - Slightly Cuter Aesthetic](https://www.nexusmods.com/stardewvalley/mods/5450).
1. Load save.
2. Open CJB Cheats Menu.
3. Click 'Time'.
4. Select '23, Spring'.
5. Goto 'bed' and 'sleep'.
6. Goto 'Flower Dance'.
7. Look, NPC outfits haven't been changed.

**Log file**
https://smapi.io/log/9f65de14701e4376bb01a709c92fd411

But if I change it to Japanese, DayEvent still uses the name 'flower dance' like in English.
https://smapi.io/log/9f78762e19804604ad5c9c756ad3b251

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/43781364/57d0384e-6a92-4faf-88bb-3e5b517472c7)

**Comment by ellipszist** [comment]
@Pathoschild

**Comment by Pathoschild** [comment]
The upcoming Content Patcher 2.1.0 adds an optional `TargetLocale` field to edit a specific asset locale. For example, you can change the Thai festival names without changing the base English asset:
```json
{
    "Action": "Load",
    "Target": "Data/Festivals/FestivalDates",
    "TargetLocale": "th",
    "Entries": {
        "spring13": "เทศกาลไข่",
        "spring24": "เทศกาลระบำดอกไม้",
        "summer11": "เทศกาลลัวร์",
        "summer28": "ระบำแมงกะพรุนแสงจันทร์",
        "fall16": "สตาร์ดิวแวลลีย์แฟร์",
        "fall27": "คืนแห่งวิญญาณ",
        "winter8": "เทศกาลน้ำแข็ง",
        "winter25": "เทศกาลแห่งดวงดาวฤดูหนาว"
    }
},
```

In the meantime, you can fix this specific case by setting the `name` field in the festival's data file instead.
