### ISSUE TITLE
Split-Screen Bug SVE/SMAPI if game is set to german

### ISSUE THREAD

**Issue by CommanderKSK** [Pathoschild/LookupAnything#879]
**Describe the bug**
If you start local split-screen mode and the game is set to german smapi trys to load Town.de-DE.xnb and produce an error.
If the game is set to english and start the split-screen mode everything works fine.
Sometimes the errors cause a black screen on the right side (player 2) after he joins and he can do nothing.
Sometimes there are only 3 errors and the second player can play normal.
If i play the same save alone i don't have any problem even if the game is set to german.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Start game 
2. Set game to german
3. Load or create new farm
4. go to settings and start local coop (split-screen mode)
5. Error occurs if the second player joins (Sometimes game breaking so it freezes or only the 2 errors and you can play)

**Log file**
In this logfile the game was set to german and the second player joined in split-screen mode, the right side (player2) went black and freezes:
https://smapi.io/log/aef2f516cd874c3a83e60019dd738cab

In this logfile the game was set to german and the second player joined in split-screen mode, this time it worked only the 3 errors occur. (This was the same save game as the log before, only played 2 days in english and then tryed again with the game set to german.)
https://smapi.io/log/d074bf0b51864938837d40e413372d5c

In this logfile the game was set to german (this is the same save as the 2 logs before but i don't startet split-screen mode) here zero errors
https://smapi.io/log/759d164d08a24889add5213f4caf157e

In this logfile i removed every mod beside SVE and created a new farm, game still set to german. Here the same 2 errors occur as the logs before.
https://smapi.io/log/2de8f472969e45c2bf2e45de54d6393a

In this logfile i removed every mod beside SVE and created a new farm but game is set to english. Here absolutely zero errors occur.
https://smapi.io/log/2fda8d79d98045ef9ea299e365734723

In this logfile i removed every installed mod beside the smapi ones, game is set to german and startet a new farm startet split-screen and no error occurs.
https://smapi.io/log/aab06123d35944d3aab1e74a91e10cc7

So my conclusion is it definitely has something to do with SVE (what farm you select has nothing to do with the outcome, if you use sve farm or original one doesn't matter).
If the game is set to german SVE wants smapi to load something it isnt there and sometimes this works and sometimes the game freezes because of that.?
But this all only occurs for the split-screen mode if i play the same save alone without split-screen i have no errors and can play without any problem.

SVE, smapi, game set to german, and starting split-screen mode here is the problem.

If you need some more information i try to help you out.

**Comment by Pathoschild** [comment]
The crash was fixed in SMAPI 4.0.8, and the upcoming Content Patcher 2.1.0 will no longer load localized variants like `Maps/Town.de-DE` for non-localized assets (see the [migration guide](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-migration-guide.md#21)). Thanks for reporting it!
