### ISSUE TITLE
[Lookup Anything] Round Mahogany Tree growth chance

### ISSUE THREAD

**Issue by Flofian** [Pathoschild/LookupAnything#886]
Stardew Valley Version 1.6.3.24087
SMAPI Version 4.0.4.0
Lookup Anything Version 1.41.4

**Describe the bug**
Mahogany Tree growth chance is displayed as 15.000001% without and 60.000004% with Tree Fertilizer, when it is probably meant to display 15% and 60%
This does not happen with Oak, Pine and Maple Trees
I have not tested Mushroom, Palm, Mystic and Green Rain Trees

**To Reproduce**
Plant Mahogany Seed
Open Lookup Anything Window

**Log file**
No Error in Logfile

**Screenshots**
![Screenshot 2024-04-04 165745](https://github.com/Pathoschild/StardewMods/assets/56082272/2677556a-a170-416c-8033-5e69bdf5c95a)
![Screenshot 2024-04-04 165818](https://github.com/Pathoschild/StardewMods/assets/56082272/6e0b24d7-2c39-4081-9ca5-2d42b6b3e680)

**Comment by Pathoschild** [comment]
Fixed in the upcoming Lookup Anything 1.42.0. Thanks to @b3nk3lly for the fix!
