### ISSUE TITLE
[Lookup Anything] Missing Name for Tree Stage 4

### ISSUE THREAD

**Issue by Flofian** [Pathoschild/LookupAnything#887]
Stardew Valley Version 1.6.3.24087
SMAPI Version 4.0.4.0
Lookup Anything Version 1.41.4

**Describe the bug**
Growth stage 4 is missing the name, it should display "small tree", but it displays "(no translation:tree.stages.4)"
The language files are structured like this:
```json
// growth stages
"tree.stages.seed": "seed",
"tree.stages.sprout": "sprout",
"tree.stages.sapling": "sapling",
"tree.stages.bush": "bush",
"tree.stages.smallTree": "small tree",
"tree.stages.tree": "tree",
```
All the other values are shown correctly, but somehow the internal name must have been changed from "tree.stages.smallTree" to "tree.stages.4"
I did not test other languages, but the files look the same

**To Reproduce**
Open the Lookup Anything on a tree thats stage 3 or stage 4

**Log file**
No Errors in the log file

**Screenshots**
![Screenshot 2024-04-04 171140](https://github.com/Pathoschild/StardewMods/assets/56082272/535ff442-3510-4655-b36a-2dbd6d30f820)
![Screenshot 2024-04-04 171157](https://github.com/Pathoschild/StardewMods/assets/56082272/13d8c443-f461-4a71-83ec-4594f8922701)

**Comment by Pathoschild** [comment]
This was fixed in Lookup Anything 1.42.0. Thanks for reporting it!
