### ISSUE TITLE
[Automate] some players experience lag

### ISSUE THREAD

**Issue by L3thal1ty** [Pathoschild/LookupAnything#89]
I have about 30+ chests automating my Junimo Huts, tappers, and smelters, and it just stutters and skips frames when moving.  Please DM me on discord if you need anything else from me. Thanks Pathos, you're a gentleman and a scholar!

[Hangy30_161463956.zip](https://github.com/Pathoschild/StardewMods/files/1207002/Hangy30_161463956.zip)

**Comment by L3thal1ty** [comment]
Update for you Pathos: I ended up not needing any more Maple Syrup so I removed the 3 chests and 10 tappers from the maple trees on the right, and the stuttering is gone. Maybe the number of tappers pushed it over some limit? I have no idea, just wanted to pass on the new information.

**Comment by Pathoschild** [comment]
Fixed in the upcoming Automate 1.6, which has a much more efficient approach to pulling items from connected chests.
