### ISSUE TITLE
[TractorMod] No audio device leads to complete failure of SMAPI

### ISSUE THREAD

**Issue by A-I-Dev** [Pathoschild/LookupAnything#891]
**Describe the bug**
On latest version, when there are no audio devices available, SMAPI throws a non-disruptive error:

`[game] Game.Initialize() caught exception initializing XACT.
Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005)`

which leads to TractorMod error:

`[game] Error loading sound: D:\Games\SVNoMods\Stardew Valley\Mods\TractorMod\assets\audio\start.ogg
Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005): Audio has failed to initialize. Call SoundEffect.Initialize() before sound operation to get more specific errors.`

which leads to complete failure of SMAPI and the game can't load.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Disable all audio devices
2. Run SMAPI with TractorMOD installed

**Log file**

https://smapi.io/log/7761099a66e848d9ae09d64a5e300050

No audio device shouldn't be a breaking error, just a warning but the game should load as normal.

**Comment by Pathoschild** [comment]
This should be fixed in the upcoming Stardew Valley 1.6.9. Thanks for reporting it!

**Comment by Pelleplast** [comment]
> This should be fixed in the upcoming Stardew Valley 1.6.9. Thanks for reporting it!

Do we have any release info about 1.6.9? I can't launch stardew valley at all with Tractor Mod installed so I have to disable it until 1.6.9

**Comment by Pathoschild** [comment]
@Pelleplast The 1.6.9 beta will be starting soon; if you're interested, you can come ping me on [the Stardew Valley Discord](https://smapi.io/community#Discord) to get access when it starts.
