### ISSUE TITLE
[automate] having paths under fishpond stops automate from working

### ISSUE THREAD

**Issue by mer2329** [Pathoschild/LookupAnything#893]
**Describe the bug**
i have automate setup to allow a few extra paths to work (config is in the logs). for the fish ponds i fill in a section with stone walkway, if you have the area under the water filled in with a path, it stops automate from pulling from it. 

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save '...'.
2. fill in a 7x7 or bigger with a path you have enabled in automate
3. place a fish pond on that spot and place a connected chest nearby
4. level up the fish pond so it starts giving you items. 
5. notice the roe stays in the bucket, like the screenshot below and hasnt been moved into the chest. (the area under the pond is the same as the area above.)

**Log file**
i dotn think it will help but. 
[](https://smapi.io/log/772f3c52fa5c4f448b32e4305eeddc87)

automate config https://smapi.io/log/7fc7aed00882440caa47e487febfc855

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/74b1bdbd-3460-451f-8e29-e6ae720c4129)

heres the fish ponds moved aside to show my paths 
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/85f3311e-aa6d-4c1a-8da3-d9944412623c)

just before getting ready to move it down
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/f09cf48b-3a85-4239-afd8-6e168d8b4dfd)

after moving and the next day 
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/365bf412-99ac-49e0-8591-9937985bff3b)
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/0b996b15-6ace-4fdd-8ced-3ca72d8c6154)

**Comment by mer2329** [comment]
about "steps to reporduce #3" the fish you put in the pond dosent matter, this bug has happened with many different fish for me, at the time of the report i had 4 ponds with this issue. but if your looking to reproduce it with my setup in the screenshots, use sturgon.

**Comment by Pathoschild** [comment]
This was fixed in Automate 2.0.6. Thanks for reporting it!
