### ISSUE TITLE
[Lookup Anything] Change character taste sorting

### ISSUE THREAD

**Issue by Icehawk78** [Pathoschild/LookupAnything#91]
It might be more useful to sort the characters' loves/likes by listing what is in your inventory first, and what is owned by you second, and then everything else, and only alphabetical after that.

I'm not nearly as familiar with C# LINQ lambdas, but I imagine you should be able to do something (in `LookupAnything/Framework/Fields/CharacterGiftTastesField.cs`) to the effect of 

    Item[] items = giftTastes[showTaste]
                            .OrderBy(x => {return Array.IndexOf(x, inventory) > -1 ? 1 : -1;})
                            .ThenBy(...).ToArray() 

as long as you move the initialization to after `ownedItems` and `inventory` have been declared.

**Comment by Pathoschild** [comment]
Hi @Icehawk78. That makes sense; I'll look into it for an upcoming release. :)

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming release.
