### ISSUE TITLE
[Automate] Seems to not always collect items from machines 

### ISSUE THREAD

**Issue by Traehgniw** [Pathoschild/LookupAnything#910]
**Describe the bug**
I noticed that some machines seemed to be taking a really long time to process things, but didn't have any reason to go into my shed at the time and thought they were processing modded recipes that took forever. However, when I did go in there to add more machines, I found several machines that were part of Automate groups and had ready-to-collect outputs that weren't being collected. Other machines in the same grouping did have their stuff collected. I collected the stuff and they got new inputs like normal. Some were modded machines, one was a vanilla machine with a modded recipe, and one was a keg with coffee. I then slept and when I went in to check after harvesting my crops some more machines had failed to collect their stuff.

**To Reproduce**

Put a bunch of machines somewhere. Add a chest and inputs. Wait until they finish and some won't collect properly. It might also be related to stuff finishing overnight so maybe stagger the inputs or use different length recipes so some finish overnight and some don't.

**Log file**
Upload your SMAPI log to https://smapi.io/log and post a link here.
https://smapi.io/log/b45a9b4ae3e9436f8ad3dbb4b8f8b14f

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/42482668/929abc4c-cea3-4f38-8ef7-1e3c7cdb85d5)

**Comment by Traehgniw** [comment]
Played some more and it doesn't seem related to sleeping the night, actually. It happened twice in a row with a seedmaker making beet seeds.

**Comment by Pathoschild** [comment]
Hi! Does that still happen if you remove Better Chests? If not, you can ask about it on that mod's page.
