### ISSUE TITLE
[Content Patcher]Baby, Toddler and Toddler_girl calling language specific assets. 

### ISSUE THREAD

**Issue by Youkonos** [Pathoschild/LookupAnything#931]
**Describe the bug**
When the language is anything other than english, all variations of the "Toddler" asset (including girl, dark etc) load the default instead of the specified content patcher patch.  The patch export for these sprites return the correct patched asset. 

**To Reproduce**
1. Change language to anything other than english
2. The toddlers will not patch correctly. 

**Log file**
https://smapi.io/log/f7f9ce11c9f24d9888f609ed3c2190ad?format=RawView

**Screenshots**
English: 
![0975e85d51b5c5d78948cab2f8399657](https://github.com/Pathoschild/StardewMods/assets/60805592/c417dcb5-4b9b-49c3-bc78-6ac7956ffa62)

Not English:
![e4bea7dd4cd9cecba92e7c65782a264e](https://github.com/Pathoschild/StardewMods/assets/60805592/5df277a2-8875-4725-be2c-831b1aba87d6)

Example mod and working save: 
[ModTester-ToddlerError.zip](https://github.com/Pathoschild/StardewMods/files/15243895/ModTester-ToddlerError.zip)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Content Patcher 2.1.0; see the [migration guide](https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-migration-guide.md#21) for more info. Thanks for reporting it!
