### ISSUE TITLE
[Automate] Does not push custom recipes to Mill

### ISSUE THREAD

**Issue by scriptsforweirdos** [Pathoschild/LookupAnything#935]
**Describe the bug**
A chest placed adjacent to a Mill containing items which should be accepted by the Mill are not automatically fed in.

**To Reproduce**
1. Create custom Building output rules for Mill via Content Patcher.
2. Place chest next to mill.
3. Insert Item which satisfies the required tags for your rule into the chest.
4. Nothing happens.

**Log file**
[Loggity log log log](https://smapi.io/log/5ff053c3882b4227ba0846fca4ddb6a8) :)

**Screenshots**
The Mill produced the item on the left via *manual* insertion of the items on the right. That chest is touching the Mill. It pulled the beets and wheat from the chest just fine.  
![Automate Mill bug](https://github.com/Pathoschild/StardewMods/assets/22039883/c8b6e824-ee88-4fcc-bd4f-701497a4c9c8)

**Sample CPatcher JSON**
(Moved to above the rule for Unmilled Rice...)  
```json
"Mill_Rye": {
                    "Id": "Mill_Rye",
                    "RequiredTags": [
                        "id_o_mymod.id_rye"
                    ],
                    "RequiredCount": 1,
                    "MaxDailyConversions": -1,
                    "SourceChest": "Input",
                    "DestinationChest": "Output",
                    "ProducedItems": [
                        {
                            "Id": "(O)Mymod.ID_RyeFlour",
                            "ItemId": "(O)Mymod.ID_RyeFlour",
                            "MinStack": 1
                        }
                    ]
                },
```

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Automate 2.1.0, which adds support for data-based building rules. Thanks for reporting it!
