### ISSUE TITLE
[Lookup Anything] Dangerous haunted Skull is identifying as a Lava Bat.

### ISSUE THREAD

**Issue by mer2329** [Pathoschild/LookupAnything#938]
**Describe the bug**
when opening lookup anything on a dangerous Haunted Skull, it is inentifying as a lava bat. including a lava bats drops, but it has the skills tile. 

**To Reproduce**
1. Load save
2. go to mines
3. make sure its in dangerous mode, if its not enable it and come back
5. locate a Haunted skull (they live on floor 71-79 (the ice section) and on dungeon floors)
6. push f1 on top of the haunted skull.
7. it identifies as a Lavabat, the table is for a lava bat, but the tile is for the haunted skull.

**Log file**
https://smapi.io/log/1a04e36140b9459b92913e5f09561e66

**Screenshots**
![image](https://github.com/Pathoschild/StardewMods/assets/6768243/cb09d183-bd1b-44f3-98f4-74e8d7220e2a)

**Comment by Pathoschild** [comment]
Hi! That's the haunted skull's actual name and drops from the game state. Their name is Lava Bat since they're just tweaked lava bats, and the extra drops for haunted skulls are hardcoded in `Bat.getExtraDropItems()` which isn't visible to Lookup Anything.
