### ISSUE TITLE
Update Spanish translations for Automate

### ISSUE THREAD

**Issue by Nana-Nord** [Pathoschild/LookupAnything#948]
![image](https://github.com/Pathoschild/StardewMods/assets/152245118/68636e51-18c8-4341-be8a-58030309a249)

Hi! 
I'm not sure if i should put the request here, but there isn't an open issue about this on the link https://github.com/StardewModders/mod-translations/issues?q=is%3Aissue+is%3Aopen  

Anyways, i was using **automate mod** and realice that some part were in **espanish** but other were in english, so i took the file from i18n and translate it.  [automate_es.json](https://github.com/Pathoschild/StardewMods/files/15370306/automate_es.json)

I hope you find it useful.
Best regards

**Comment by Pathoschild** [comment]
Added in `develop` for the upcoming Automate 2.1.0. Thanks for the help!
