### ISSUE TITLE
[Lookup Anything] LocalizedText not working in name with Custom Bush compatibility

### ISSUE THREAD

**Issue by 6480k** [Pathoschild/LookupAnything#969]
**Describe the bug**
When adding a DisplayName field to LeFauxMatt's Custom Bush data for Lookup Anything integration, utilizing vanilla game strings via the LocalizedText feature displays the field exactly as it is.
For example:
In Custom Bush data -- `"DisplayName": "[LocalizedText Strings\\Objects:Blueberry_Name]",` (copied from vanilla Object data)
When using LA ingame -- bush displays as `[LocalizedText Strings\Objects:Blueberry_Name]`

The vanilla strings could be duplicated within the mod for use with i18n instead, but this may lead to inconsistencies in translation/more work for translators. I'm not sure whether this is considered a bug or not.

**To Reproduce**
Download and install attached demo mod (Growable Forage and Crop Bushes beta) (bush data is in data/teabushes.json)
Download and install attached Custom Bush (or download from Nexus)
Plant any of the bush planting items (such as Morel Planter or Blueberry Sapling)
Use latest Lookup Anything to look up the bush data

**Log file**
https://smapi.io/log/f2b70bfea0cf4190846ca49cac07f27d

**Screenshots**
![](https://i.imgur.com/EYvs3UI.png)
[[CP] Growable Forage and Crop Bushes.zip](https://github.com/Pathoschild/StardewMods/files/15410911/CP.Growable.Forage.and.Crop.Bushes.zip)
[CustomBush.zip](https://github.com/Pathoschild/StardewMods/files/15410914/CustomBush.zip)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Lookup Anything 1.44.0. Thanks for reporting it!
